services:
  frontend:
    build:
      context: ..
      dockerfile: .docker_102/Dockerfile
    container_name: frontend_container_102
    volumes:
      - ../src:/usr/src/app/src 
    ports:
      - "3000:3003"
    networks:
      - prod_network
    restart: always

networks:
  prod_network:
    name: prod_network
    external: true
