server {
    listen 3003;
    server_name deepbim.net;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
     # Cấu hình phục vụ file maintenance
    location = /maintenance.html {
        root /var/www/html;  # đường dẫn chứa maintenance.html
        internal;xxxx
    }
}
