/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedHowItWorksImport } from './routes/_authenticated/how-it-works'
import { Route as AuthenticatedFeaturesImport } from './routes/_authenticated/features'
import { Route as AuthenticatedContactUsImport } from './routes/_authenticated/contact-us'
import { Route as authVerifyEmailImport } from './routes/(auth)/verify-email'
import { Route as authSignInImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordImport } from './routes/(auth)/reset-password'
import { Route as authCallbackImport } from './routes/(auth)/callback'
import { Route as auth500Import } from './routes/(auth)/500'
import { Route as ExampleModelIfcIndexImport } from './routes/example-model/ifc/index'
import { Route as AuthenticatedViewIndexImport } from './routes/_authenticated/view/index'
import { Route as AuthenticatedMyRoom3dIndexImport } from './routes/_authenticated/my-room-3d/index'
import { Route as AuthenticatedAppIndexImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedViewFileCodeImport } from './routes/_authenticated/view/$fileCode'
import { Route as AuthenticatedManagementsLayoutImport } from './routes/_authenticated/managements/_layout'
import { Route as AuthenticatedBlogLayoutImport } from './routes/_authenticated/blog/_layout'
import { Route as AuthenticatedBimViewerUtWebglClippingV2Import } from './routes/_authenticated/bim-viewer-ut/webgl-clipping-v2'
import { Route as AuthenticatedBimViewerUtWebglClippingV1Import } from './routes/_authenticated/bim-viewer-ut/webgl-clipping-v1'
import { Route as AuthenticatedBimViewerUtWebglClippingStencilIfcImport } from './routes/_authenticated/bim-viewer-ut/webgl-clipping-stencil-ifc'
import { Route as AuthenticatedBimViewerUtWebglClippingStencilImport } from './routes/_authenticated/bim-viewer-ut/webgl-clipping-stencil'
import { Route as AuthenticatedBimViewerUtWebglClippingCubeImport } from './routes/_authenticated/bim-viewer-ut/webgl-clipping-cube'
import { Route as AuthenticatedBimViewerUtViewCubeImport } from './routes/_authenticated/bim-viewer-ut/view-cube'
import { Route as AuthenticatedBimViewerUtIfcViewerSelectionFamilyImport } from './routes/_authenticated/bim-viewer-ut/ifc-viewer-selection-family'
import { Route as AuthenticatedBimViewerUtGeometrySceneViewcubeImport } from './routes/_authenticated/bim-viewer-ut/geometry-scene-viewcube'
import { Route as AuthenticatedBimViewerUtIfcViewerSelectionImport } from './routes/_authenticated/bim-viewer-ut/Ifc-viewer-selection'
import { Route as AuthenticatedAppLayoutImport } from './routes/_authenticated/app/_layout'
import { Route as AuthenticatedAdminLayoutImport } from './routes/_authenticated/admin/_layout'
import { Route as AuthenticatedViewUploadIndexImport } from './routes/_authenticated/view/upload/index'
import { Route as AuthenticatedManagementsLayoutUsersImport } from './routes/_authenticated/managements/_layout/users'
import { Route as AuthenticatedManagementsLayoutSpacesImport } from './routes/_authenticated/managements/_layout/spaces'
import { Route as AuthenticatedManagementsLayoutProjectsImport } from './routes/_authenticated/managements/_layout/projects'
import { Route as AuthenticatedManagementsLayoutMeImport } from './routes/_authenticated/managements/_layout/me'
import { Route as AuthenticatedManagementsLayoutHomeImport } from './routes/_authenticated/managements/_layout/home'
import { Route as AuthenticatedManagementsLayoutCloudImport } from './routes/_authenticated/managements/_layout/cloud'
import { Route as AuthenticatedManagementsLayoutChatSupportImport } from './routes/_authenticated/managements/_layout/chat-support'
import { Route as AuthenticatedBlogLayoutContactImport } from './routes/_authenticated/blog/_layout/contact'
import { Route as AuthenticatedBlogLayoutAboutImport } from './routes/_authenticated/blog/_layout/about'
import { Route as AuthenticatedAppLayoutHowItWorksImport } from './routes/_authenticated/app/_layout/how-it-works'
import { Route as AuthenticatedAppLayoutFeaturesImport } from './routes/_authenticated/app/_layout/features'
import { Route as AuthenticatedAppLayoutContactUsImport } from './routes/_authenticated/app/_layout/contact-us'
import { Route as AuthenticatedAppLayoutConnectorsImport } from './routes/_authenticated/app/_layout/connectors'
import { Route as AuthenticatedUserShowPortfolioIndexImport } from './routes/_authenticated/user/show/portfolio/index'
import { Route as AuthenticatedUserShowCvIndexImport } from './routes/_authenticated/user/show/cv/index'
import { Route as AuthenticatedManagementsLayoutTeamsIndexImport } from './routes/_authenticated/managements/_layout/teams/index'
import { Route as AuthenticatedManagementsLayoutSubProjectsIndexImport } from './routes/_authenticated/managements/_layout/sub-projects/index'
import { Route as AuthenticatedUserShowProfileLayoutImport } from './routes/_authenticated/user/show/profile/_layout'
import { Route as AuthenticatedManagementsLayoutTeamsTeamIdImport } from './routes/_authenticated/managements/_layout/teams/$teamId'
import { Route as AuthenticatedManagementsLayoutSubProjectsSubprojectidImport } from './routes/_authenticated/managements/_layout/sub-projects/$sub_project_id'
import { Route as AuthenticatedUserShowProfileLayoutIndexImport } from './routes/_authenticated/user/show/profile/_layout/index'
import { Route as AuthenticatedUserShowProfileLayoutIdUserImport } from './routes/_authenticated/user/show/profile/_layout/$idUser'
import { Route as AuthenticatedUserSettingsProfileEditLayoutImport } from './routes/_authenticated/user/settings/profile/edit/_layout'
import { Route as AuthenticatedUserSettingsProfileEditLayoutIdUserImport } from './routes/_authenticated/user/settings/profile/edit/_layout/$idUser'

// Create Virtual Routes

const AuthenticatedManagementsImport = createFileRoute(
  '/_authenticated/managements',
)()
const AuthenticatedBlogImport = createFileRoute('/_authenticated/blog')()
const AuthenticatedAppImport = createFileRoute('/_authenticated/app')()
const AuthenticatedAdminImport = createFileRoute('/_authenticated/admin')()
const errors503LazyImport = createFileRoute('/(errors)/503')()
const errors500LazyImport = createFileRoute('/(errors)/500')()
const errors404LazyImport = createFileRoute('/(errors)/404')()
const errors403LazyImport = createFileRoute('/(errors)/403')()
const errors401LazyImport = createFileRoute('/(errors)/401')()
const authSignUpLazyImport = createFileRoute('/(auth)/sign-up')()
const authSignIn2LazyImport = createFileRoute('/(auth)/sign-in-2')()
const authForgotPasswordLazyImport = createFileRoute(
  '/(auth)/forgot-password',
)()
const AuthenticatedBimViewerUtViewerLazyImport = createFileRoute(
  '/_authenticated/bim-viewer-ut/viewer',
)()
const AuthenticatedBimViewerUtInstancedMeshLazyImport = createFileRoute(
  '/_authenticated/bim-viewer-ut/instanced-mesh',
)()
const AuthenticatedBimViewerUtIfcLoaderLazyImport = createFileRoute(
  '/_authenticated/bim-viewer-ut/ifc-loader',
)()
const AuthenticatedUserShowProfileImport = createFileRoute(
  '/_authenticated/user/show/profile',
)()
const AuthenticatedUserSettingsProfileEditImport = createFileRoute(
  '/_authenticated/user/settings/profile/edit',
)()

// Create/Update Routes

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedManagementsRoute = AuthenticatedManagementsImport.update({
  id: '/managements',
  path: '/managements',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedBlogRoute = AuthenticatedBlogImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedAppRoute = AuthenticatedAppImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedAdminRoute = AuthenticatedAdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const errors503LazyRoute = errors503LazyImport
  .update({
    id: '/(errors)/503',
    path: '/503',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/503.lazy').then((d) => d.Route))

const errors500LazyRoute = errors500LazyImport
  .update({
    id: '/(errors)/500',
    path: '/500',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/500.lazy').then((d) => d.Route))

const errors404LazyRoute = errors404LazyImport
  .update({
    id: '/(errors)/404',
    path: '/404',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/404.lazy').then((d) => d.Route))

const errors403LazyRoute = errors403LazyImport
  .update({
    id: '/(errors)/403',
    path: '/403',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/403.lazy').then((d) => d.Route))

const errors401LazyRoute = errors401LazyImport
  .update({
    id: '/(errors)/401',
    path: '/401',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/401.lazy').then((d) => d.Route))

const authSignUpLazyRoute = authSignUpLazyImport
  .update({
    id: '/(auth)/sign-up',
    path: '/sign-up',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-up.lazy').then((d) => d.Route))

const authSignIn2LazyRoute = authSignIn2LazyImport
  .update({
    id: '/(auth)/sign-in-2',
    path: '/sign-in-2',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-in-2.lazy').then((d) => d.Route))

const authForgotPasswordLazyRoute = authForgotPasswordLazyImport
  .update({
    id: '/(auth)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/forgot-password.lazy').then((d) => d.Route),
  )

const AuthenticatedHowItWorksRoute = AuthenticatedHowItWorksImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedFeaturesRoute = AuthenticatedFeaturesImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedContactUsRoute = AuthenticatedContactUsImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const authVerifyEmailRoute = authVerifyEmailImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRoute,
} as any)

const authSignInRoute = authSignInImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const authResetPasswordRoute = authResetPasswordImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const authCallbackRoute = authCallbackImport.update({
  id: '/(auth)/callback',
  path: '/callback',
  getParentRoute: () => rootRoute,
} as any)

const auth500Route = auth500Import.update({
  id: '/(auth)/500',
  path: '/500',
  getParentRoute: () => rootRoute,
} as any)

const ExampleModelIfcIndexRoute = ExampleModelIfcIndexImport.update({
  id: '/example-model/ifc/',
  path: '/example-model/ifc/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedViewIndexRoute = AuthenticatedViewIndexImport.update({
  id: '/view/',
  path: '/view/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedMyRoom3dIndexRoute = AuthenticatedMyRoom3dIndexImport.update(
  {
    id: '/my-room-3d/',
    path: '/my-room-3d/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
)

const AuthenticatedAppIndexRoute = AuthenticatedAppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

const AuthenticatedBimViewerUtViewerLazyRoute =
  AuthenticatedBimViewerUtViewerLazyImport.update({
    id: '/bim-viewer-ut/viewer',
    path: '/bim-viewer-ut/viewer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/bim-viewer-ut/viewer.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedBimViewerUtInstancedMeshLazyRoute =
  AuthenticatedBimViewerUtInstancedMeshLazyImport.update({
    id: '/bim-viewer-ut/instanced-mesh',
    path: '/bim-viewer-ut/instanced-mesh',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/bim-viewer-ut/instanced-mesh.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedBimViewerUtIfcLoaderLazyRoute =
  AuthenticatedBimViewerUtIfcLoaderLazyImport.update({
    id: '/bim-viewer-ut/ifc-loader',
    path: '/bim-viewer-ut/ifc-loader',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/bim-viewer-ut/ifc-loader.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedViewFileCodeRoute = AuthenticatedViewFileCodeImport.update({
  id: '/view/$fileCode',
  path: '/view/$fileCode',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedManagementsLayoutRoute =
  AuthenticatedManagementsLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => AuthenticatedManagementsRoute,
  } as any)

const AuthenticatedBlogLayoutRoute = AuthenticatedBlogLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AuthenticatedBlogRoute,
} as any)

const AuthenticatedBimViewerUtWebglClippingV2Route =
  AuthenticatedBimViewerUtWebglClippingV2Import.update({
    id: '/bim-viewer-ut/webgl-clipping-v2',
    path: '/bim-viewer-ut/webgl-clipping-v2',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedBimViewerUtWebglClippingV1Route =
  AuthenticatedBimViewerUtWebglClippingV1Import.update({
    id: '/bim-viewer-ut/webgl-clipping-v1',
    path: '/bim-viewer-ut/webgl-clipping-v1',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedBimViewerUtWebglClippingStencilIfcRoute =
  AuthenticatedBimViewerUtWebglClippingStencilIfcImport.update({
    id: '/bim-viewer-ut/webgl-clipping-stencil-ifc',
    path: '/bim-viewer-ut/webgl-clipping-stencil-ifc',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedBimViewerUtWebglClippingStencilRoute =
  AuthenticatedBimViewerUtWebglClippingStencilImport.update({
    id: '/bim-viewer-ut/webgl-clipping-stencil',
    path: '/bim-viewer-ut/webgl-clipping-stencil',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedBimViewerUtWebglClippingCubeRoute =
  AuthenticatedBimViewerUtWebglClippingCubeImport.update({
    id: '/bim-viewer-ut/webgl-clipping-cube',
    path: '/bim-viewer-ut/webgl-clipping-cube',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedBimViewerUtViewCubeRoute =
  AuthenticatedBimViewerUtViewCubeImport.update({
    id: '/bim-viewer-ut/view-cube',
    path: '/bim-viewer-ut/view-cube',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedBimViewerUtIfcViewerSelectionFamilyRoute =
  AuthenticatedBimViewerUtIfcViewerSelectionFamilyImport.update({
    id: '/bim-viewer-ut/ifc-viewer-selection-family',
    path: '/bim-viewer-ut/ifc-viewer-selection-family',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedBimViewerUtGeometrySceneViewcubeRoute =
  AuthenticatedBimViewerUtGeometrySceneViewcubeImport.update({
    id: '/bim-viewer-ut/geometry-scene-viewcube',
    path: '/bim-viewer-ut/geometry-scene-viewcube',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedBimViewerUtIfcViewerSelectionRoute =
  AuthenticatedBimViewerUtIfcViewerSelectionImport.update({
    id: '/bim-viewer-ut/Ifc-viewer-selection',
    path: '/bim-viewer-ut/Ifc-viewer-selection',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedAppLayoutRoute = AuthenticatedAppLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

const AuthenticatedAdminLayoutRoute = AuthenticatedAdminLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

const AuthenticatedUserShowProfileRoute =
  AuthenticatedUserShowProfileImport.update({
    id: '/user/show/profile',
    path: '/user/show/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedViewUploadIndexRoute =
  AuthenticatedViewUploadIndexImport.update({
    id: '/view/upload/',
    path: '/view/upload/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedManagementsLayoutUsersRoute =
  AuthenticatedManagementsLayoutUsersImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedManagementsLayoutRoute,
  } as any)

const AuthenticatedManagementsLayoutSpacesRoute =
  AuthenticatedManagementsLayoutSpacesImport.update({
    id: '/spaces',
    path: '/spaces',
    getParentRoute: () => AuthenticatedManagementsLayoutRoute,
  } as any)

const AuthenticatedManagementsLayoutProjectsRoute =
  AuthenticatedManagementsLayoutProjectsImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedManagementsLayoutRoute,
  } as any)

const AuthenticatedManagementsLayoutMeRoute =
  AuthenticatedManagementsLayoutMeImport.update({
    id: '/me',
    path: '/me',
    getParentRoute: () => AuthenticatedManagementsLayoutRoute,
  } as any)

const AuthenticatedManagementsLayoutHomeRoute =
  AuthenticatedManagementsLayoutHomeImport.update({
    id: '/home',
    path: '/home',
    getParentRoute: () => AuthenticatedManagementsLayoutRoute,
  } as any)

const AuthenticatedManagementsLayoutCloudRoute =
  AuthenticatedManagementsLayoutCloudImport.update({
    id: '/cloud',
    path: '/cloud',
    getParentRoute: () => AuthenticatedManagementsLayoutRoute,
  } as any)

const AuthenticatedManagementsLayoutChatSupportRoute =
  AuthenticatedManagementsLayoutChatSupportImport.update({
    id: '/chat-support',
    path: '/chat-support',
    getParentRoute: () => AuthenticatedManagementsLayoutRoute,
  } as any)

const AuthenticatedBlogLayoutContactRoute =
  AuthenticatedBlogLayoutContactImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => AuthenticatedBlogLayoutRoute,
  } as any)

const AuthenticatedBlogLayoutAboutRoute =
  AuthenticatedBlogLayoutAboutImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => AuthenticatedBlogLayoutRoute,
  } as any)

const AuthenticatedAppLayoutHowItWorksRoute =
  AuthenticatedAppLayoutHowItWorksImport.update({
    id: '/how-it-works',
    path: '/how-it-works',
    getParentRoute: () => AuthenticatedAppLayoutRoute,
  } as any)

const AuthenticatedAppLayoutFeaturesRoute =
  AuthenticatedAppLayoutFeaturesImport.update({
    id: '/features',
    path: '/features',
    getParentRoute: () => AuthenticatedAppLayoutRoute,
  } as any)

const AuthenticatedAppLayoutContactUsRoute =
  AuthenticatedAppLayoutContactUsImport.update({
    id: '/contact-us',
    path: '/contact-us',
    getParentRoute: () => AuthenticatedAppLayoutRoute,
  } as any)

const AuthenticatedAppLayoutConnectorsRoute =
  AuthenticatedAppLayoutConnectorsImport.update({
    id: '/connectors',
    path: '/connectors',
    getParentRoute: () => AuthenticatedAppLayoutRoute,
  } as any)

const AuthenticatedUserSettingsProfileEditRoute =
  AuthenticatedUserSettingsProfileEditImport.update({
    id: '/user/settings/profile/edit',
    path: '/user/settings/profile/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedUserShowPortfolioIndexRoute =
  AuthenticatedUserShowPortfolioIndexImport.update({
    id: '/user/show/portfolio/',
    path: '/user/show/portfolio/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedUserShowCvIndexRoute =
  AuthenticatedUserShowCvIndexImport.update({
    id: '/user/show/cv/',
    path: '/user/show/cv/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedManagementsLayoutTeamsIndexRoute =
  AuthenticatedManagementsLayoutTeamsIndexImport.update({
    id: '/teams/',
    path: '/teams/',
    getParentRoute: () => AuthenticatedManagementsLayoutRoute,
  } as any)

const AuthenticatedManagementsLayoutSubProjectsIndexRoute =
  AuthenticatedManagementsLayoutSubProjectsIndexImport.update({
    id: '/sub-projects/',
    path: '/sub-projects/',
    getParentRoute: () => AuthenticatedManagementsLayoutRoute,
  } as any)

const AuthenticatedUserShowProfileLayoutRoute =
  AuthenticatedUserShowProfileLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => AuthenticatedUserShowProfileRoute,
  } as any)

const AuthenticatedManagementsLayoutTeamsTeamIdRoute =
  AuthenticatedManagementsLayoutTeamsTeamIdImport.update({
    id: '/teams/$teamId',
    path: '/teams/$teamId',
    getParentRoute: () => AuthenticatedManagementsLayoutRoute,
  } as any)

const AuthenticatedManagementsLayoutSubProjectsSubprojectidRoute =
  AuthenticatedManagementsLayoutSubProjectsSubprojectidImport.update({
    id: '/sub-projects/$sub_project_id',
    path: '/sub-projects/$sub_project_id',
    getParentRoute: () => AuthenticatedManagementsLayoutRoute,
  } as any)

const AuthenticatedUserShowProfileLayoutIndexRoute =
  AuthenticatedUserShowProfileLayoutIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedUserShowProfileLayoutRoute,
  } as any)

const AuthenticatedUserShowProfileLayoutIdUserRoute =
  AuthenticatedUserShowProfileLayoutIdUserImport.update({
    id: '/$idUser',
    path: '/$idUser',
    getParentRoute: () => AuthenticatedUserShowProfileLayoutRoute,
  } as any)

const AuthenticatedUserSettingsProfileEditLayoutRoute =
  AuthenticatedUserSettingsProfileEditLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => AuthenticatedUserSettingsProfileEditRoute,
  } as any)

const AuthenticatedUserSettingsProfileEditLayoutIdUserRoute =
  AuthenticatedUserSettingsProfileEditLayoutIdUserImport.update({
    id: '/$idUser',
    path: '/$idUser',
    getParentRoute: () => AuthenticatedUserSettingsProfileEditLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/500': {
      id: '/(auth)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof auth500Import
      parentRoute: typeof rootRoute
    }
    '/(auth)/callback': {
      id: '/(auth)/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof authCallbackImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/contact-us': {
      id: '/_authenticated/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof AuthenticatedContactUsImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/features': {
      id: '/_authenticated/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof AuthenticatedFeaturesImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/how-it-works': {
      id: '/_authenticated/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof AuthenticatedHowItWorksImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2LazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpLazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503LazyImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/admin/_layout': {
      id: '/_authenticated/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminLayoutImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/app/_layout': {
      id: '/_authenticated/app/_layout'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppLayoutImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/bim-viewer-ut/Ifc-viewer-selection': {
      id: '/_authenticated/bim-viewer-ut/Ifc-viewer-selection'
      path: '/bim-viewer-ut/Ifc-viewer-selection'
      fullPath: '/bim-viewer-ut/Ifc-viewer-selection'
      preLoaderRoute: typeof AuthenticatedBimViewerUtIfcViewerSelectionImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/bim-viewer-ut/geometry-scene-viewcube': {
      id: '/_authenticated/bim-viewer-ut/geometry-scene-viewcube'
      path: '/bim-viewer-ut/geometry-scene-viewcube'
      fullPath: '/bim-viewer-ut/geometry-scene-viewcube'
      preLoaderRoute: typeof AuthenticatedBimViewerUtGeometrySceneViewcubeImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/bim-viewer-ut/ifc-viewer-selection-family': {
      id: '/_authenticated/bim-viewer-ut/ifc-viewer-selection-family'
      path: '/bim-viewer-ut/ifc-viewer-selection-family'
      fullPath: '/bim-viewer-ut/ifc-viewer-selection-family'
      preLoaderRoute: typeof AuthenticatedBimViewerUtIfcViewerSelectionFamilyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/bim-viewer-ut/view-cube': {
      id: '/_authenticated/bim-viewer-ut/view-cube'
      path: '/bim-viewer-ut/view-cube'
      fullPath: '/bim-viewer-ut/view-cube'
      preLoaderRoute: typeof AuthenticatedBimViewerUtViewCubeImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/bim-viewer-ut/webgl-clipping-cube': {
      id: '/_authenticated/bim-viewer-ut/webgl-clipping-cube'
      path: '/bim-viewer-ut/webgl-clipping-cube'
      fullPath: '/bim-viewer-ut/webgl-clipping-cube'
      preLoaderRoute: typeof AuthenticatedBimViewerUtWebglClippingCubeImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/bim-viewer-ut/webgl-clipping-stencil': {
      id: '/_authenticated/bim-viewer-ut/webgl-clipping-stencil'
      path: '/bim-viewer-ut/webgl-clipping-stencil'
      fullPath: '/bim-viewer-ut/webgl-clipping-stencil'
      preLoaderRoute: typeof AuthenticatedBimViewerUtWebglClippingStencilImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/bim-viewer-ut/webgl-clipping-stencil-ifc': {
      id: '/_authenticated/bim-viewer-ut/webgl-clipping-stencil-ifc'
      path: '/bim-viewer-ut/webgl-clipping-stencil-ifc'
      fullPath: '/bim-viewer-ut/webgl-clipping-stencil-ifc'
      preLoaderRoute: typeof AuthenticatedBimViewerUtWebglClippingStencilIfcImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/bim-viewer-ut/webgl-clipping-v1': {
      id: '/_authenticated/bim-viewer-ut/webgl-clipping-v1'
      path: '/bim-viewer-ut/webgl-clipping-v1'
      fullPath: '/bim-viewer-ut/webgl-clipping-v1'
      preLoaderRoute: typeof AuthenticatedBimViewerUtWebglClippingV1Import
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/bim-viewer-ut/webgl-clipping-v2': {
      id: '/_authenticated/bim-viewer-ut/webgl-clipping-v2'
      path: '/bim-viewer-ut/webgl-clipping-v2'
      fullPath: '/bim-viewer-ut/webgl-clipping-v2'
      preLoaderRoute: typeof AuthenticatedBimViewerUtWebglClippingV2Import
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/blog': {
      id: '/_authenticated/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof AuthenticatedBlogImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/blog/_layout': {
      id: '/_authenticated/blog/_layout'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof AuthenticatedBlogLayoutImport
      parentRoute: typeof AuthenticatedBlogRoute
    }
    '/_authenticated/managements': {
      id: '/_authenticated/managements'
      path: '/managements'
      fullPath: '/managements'
      preLoaderRoute: typeof AuthenticatedManagementsImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/managements/_layout': {
      id: '/_authenticated/managements/_layout'
      path: '/managements'
      fullPath: '/managements'
      preLoaderRoute: typeof AuthenticatedManagementsLayoutImport
      parentRoute: typeof AuthenticatedManagementsRoute
    }
    '/_authenticated/view/$fileCode': {
      id: '/_authenticated/view/$fileCode'
      path: '/view/$fileCode'
      fullPath: '/view/$fileCode'
      preLoaderRoute: typeof AuthenticatedViewFileCodeImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/bim-viewer-ut/ifc-loader': {
      id: '/_authenticated/bim-viewer-ut/ifc-loader'
      path: '/bim-viewer-ut/ifc-loader'
      fullPath: '/bim-viewer-ut/ifc-loader'
      preLoaderRoute: typeof AuthenticatedBimViewerUtIfcLoaderLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/bim-viewer-ut/instanced-mesh': {
      id: '/_authenticated/bim-viewer-ut/instanced-mesh'
      path: '/bim-viewer-ut/instanced-mesh'
      fullPath: '/bim-viewer-ut/instanced-mesh'
      preLoaderRoute: typeof AuthenticatedBimViewerUtInstancedMeshLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/bim-viewer-ut/viewer': {
      id: '/_authenticated/bim-viewer-ut/viewer'
      path: '/bim-viewer-ut/viewer'
      fullPath: '/bim-viewer-ut/viewer'
      preLoaderRoute: typeof AuthenticatedBimViewerUtViewerLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexImport
      parentRoute: typeof AuthenticatedAppImport
    }
    '/_authenticated/my-room-3d/': {
      id: '/_authenticated/my-room-3d/'
      path: '/my-room-3d'
      fullPath: '/my-room-3d'
      preLoaderRoute: typeof AuthenticatedMyRoom3dIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/view/': {
      id: '/_authenticated/view/'
      path: '/view'
      fullPath: '/view'
      preLoaderRoute: typeof AuthenticatedViewIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/example-model/ifc/': {
      id: '/example-model/ifc/'
      path: '/example-model/ifc'
      fullPath: '/example-model/ifc'
      preLoaderRoute: typeof ExampleModelIfcIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/app/_layout/connectors': {
      id: '/_authenticated/app/_layout/connectors'
      path: '/connectors'
      fullPath: '/app/connectors'
      preLoaderRoute: typeof AuthenticatedAppLayoutConnectorsImport
      parentRoute: typeof AuthenticatedAppLayoutImport
    }
    '/_authenticated/app/_layout/contact-us': {
      id: '/_authenticated/app/_layout/contact-us'
      path: '/contact-us'
      fullPath: '/app/contact-us'
      preLoaderRoute: typeof AuthenticatedAppLayoutContactUsImport
      parentRoute: typeof AuthenticatedAppLayoutImport
    }
    '/_authenticated/app/_layout/features': {
      id: '/_authenticated/app/_layout/features'
      path: '/features'
      fullPath: '/app/features'
      preLoaderRoute: typeof AuthenticatedAppLayoutFeaturesImport
      parentRoute: typeof AuthenticatedAppLayoutImport
    }
    '/_authenticated/app/_layout/how-it-works': {
      id: '/_authenticated/app/_layout/how-it-works'
      path: '/how-it-works'
      fullPath: '/app/how-it-works'
      preLoaderRoute: typeof AuthenticatedAppLayoutHowItWorksImport
      parentRoute: typeof AuthenticatedAppLayoutImport
    }
    '/_authenticated/blog/_layout/about': {
      id: '/_authenticated/blog/_layout/about'
      path: '/about'
      fullPath: '/blog/about'
      preLoaderRoute: typeof AuthenticatedBlogLayoutAboutImport
      parentRoute: typeof AuthenticatedBlogLayoutImport
    }
    '/_authenticated/blog/_layout/contact': {
      id: '/_authenticated/blog/_layout/contact'
      path: '/contact'
      fullPath: '/blog/contact'
      preLoaderRoute: typeof AuthenticatedBlogLayoutContactImport
      parentRoute: typeof AuthenticatedBlogLayoutImport
    }
    '/_authenticated/managements/_layout/chat-support': {
      id: '/_authenticated/managements/_layout/chat-support'
      path: '/chat-support'
      fullPath: '/managements/chat-support'
      preLoaderRoute: typeof AuthenticatedManagementsLayoutChatSupportImport
      parentRoute: typeof AuthenticatedManagementsLayoutImport
    }
    '/_authenticated/managements/_layout/cloud': {
      id: '/_authenticated/managements/_layout/cloud'
      path: '/cloud'
      fullPath: '/managements/cloud'
      preLoaderRoute: typeof AuthenticatedManagementsLayoutCloudImport
      parentRoute: typeof AuthenticatedManagementsLayoutImport
    }
    '/_authenticated/managements/_layout/home': {
      id: '/_authenticated/managements/_layout/home'
      path: '/home'
      fullPath: '/managements/home'
      preLoaderRoute: typeof AuthenticatedManagementsLayoutHomeImport
      parentRoute: typeof AuthenticatedManagementsLayoutImport
    }
    '/_authenticated/managements/_layout/me': {
      id: '/_authenticated/managements/_layout/me'
      path: '/me'
      fullPath: '/managements/me'
      preLoaderRoute: typeof AuthenticatedManagementsLayoutMeImport
      parentRoute: typeof AuthenticatedManagementsLayoutImport
    }
    '/_authenticated/managements/_layout/projects': {
      id: '/_authenticated/managements/_layout/projects'
      path: '/projects'
      fullPath: '/managements/projects'
      preLoaderRoute: typeof AuthenticatedManagementsLayoutProjectsImport
      parentRoute: typeof AuthenticatedManagementsLayoutImport
    }
    '/_authenticated/managements/_layout/spaces': {
      id: '/_authenticated/managements/_layout/spaces'
      path: '/spaces'
      fullPath: '/managements/spaces'
      preLoaderRoute: typeof AuthenticatedManagementsLayoutSpacesImport
      parentRoute: typeof AuthenticatedManagementsLayoutImport
    }
    '/_authenticated/managements/_layout/users': {
      id: '/_authenticated/managements/_layout/users'
      path: '/users'
      fullPath: '/managements/users'
      preLoaderRoute: typeof AuthenticatedManagementsLayoutUsersImport
      parentRoute: typeof AuthenticatedManagementsLayoutImport
    }
    '/_authenticated/view/upload/': {
      id: '/_authenticated/view/upload/'
      path: '/view/upload'
      fullPath: '/view/upload'
      preLoaderRoute: typeof AuthenticatedViewUploadIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/managements/_layout/sub-projects/$sub_project_id': {
      id: '/_authenticated/managements/_layout/sub-projects/$sub_project_id'
      path: '/sub-projects/$sub_project_id'
      fullPath: '/managements/sub-projects/$sub_project_id'
      preLoaderRoute: typeof AuthenticatedManagementsLayoutSubProjectsSubprojectidImport
      parentRoute: typeof AuthenticatedManagementsLayoutImport
    }
    '/_authenticated/managements/_layout/teams/$teamId': {
      id: '/_authenticated/managements/_layout/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/managements/teams/$teamId'
      preLoaderRoute: typeof AuthenticatedManagementsLayoutTeamsTeamIdImport
      parentRoute: typeof AuthenticatedManagementsLayoutImport
    }
    '/_authenticated/user/show/profile': {
      id: '/_authenticated/user/show/profile'
      path: '/user/show/profile'
      fullPath: '/user/show/profile'
      preLoaderRoute: typeof AuthenticatedUserShowProfileImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/user/show/profile/_layout': {
      id: '/_authenticated/user/show/profile/_layout'
      path: '/user/show/profile'
      fullPath: '/user/show/profile'
      preLoaderRoute: typeof AuthenticatedUserShowProfileLayoutImport
      parentRoute: typeof AuthenticatedUserShowProfileRoute
    }
    '/_authenticated/managements/_layout/sub-projects/': {
      id: '/_authenticated/managements/_layout/sub-projects/'
      path: '/sub-projects'
      fullPath: '/managements/sub-projects'
      preLoaderRoute: typeof AuthenticatedManagementsLayoutSubProjectsIndexImport
      parentRoute: typeof AuthenticatedManagementsLayoutImport
    }
    '/_authenticated/managements/_layout/teams/': {
      id: '/_authenticated/managements/_layout/teams/'
      path: '/teams'
      fullPath: '/managements/teams'
      preLoaderRoute: typeof AuthenticatedManagementsLayoutTeamsIndexImport
      parentRoute: typeof AuthenticatedManagementsLayoutImport
    }
    '/_authenticated/user/show/cv/': {
      id: '/_authenticated/user/show/cv/'
      path: '/user/show/cv'
      fullPath: '/user/show/cv'
      preLoaderRoute: typeof AuthenticatedUserShowCvIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/user/show/portfolio/': {
      id: '/_authenticated/user/show/portfolio/'
      path: '/user/show/portfolio'
      fullPath: '/user/show/portfolio'
      preLoaderRoute: typeof AuthenticatedUserShowPortfolioIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/user/settings/profile/edit': {
      id: '/_authenticated/user/settings/profile/edit'
      path: '/user/settings/profile/edit'
      fullPath: '/user/settings/profile/edit'
      preLoaderRoute: typeof AuthenticatedUserSettingsProfileEditImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/user/settings/profile/edit/_layout': {
      id: '/_authenticated/user/settings/profile/edit/_layout'
      path: '/user/settings/profile/edit'
      fullPath: '/user/settings/profile/edit'
      preLoaderRoute: typeof AuthenticatedUserSettingsProfileEditLayoutImport
      parentRoute: typeof AuthenticatedUserSettingsProfileEditRoute
    }
    '/_authenticated/user/show/profile/_layout/$idUser': {
      id: '/_authenticated/user/show/profile/_layout/$idUser'
      path: '/$idUser'
      fullPath: '/user/show/profile/$idUser'
      preLoaderRoute: typeof AuthenticatedUserShowProfileLayoutIdUserImport
      parentRoute: typeof AuthenticatedUserShowProfileLayoutImport
    }
    '/_authenticated/user/show/profile/_layout/': {
      id: '/_authenticated/user/show/profile/_layout/'
      path: '/'
      fullPath: '/user/show/profile/'
      preLoaderRoute: typeof AuthenticatedUserShowProfileLayoutIndexImport
      parentRoute: typeof AuthenticatedUserShowProfileLayoutImport
    }
    '/_authenticated/user/settings/profile/edit/_layout/$idUser': {
      id: '/_authenticated/user/settings/profile/edit/_layout/$idUser'
      path: '/$idUser'
      fullPath: '/user/settings/profile/edit/$idUser'
      preLoaderRoute: typeof AuthenticatedUserSettingsProfileEditLayoutIdUserImport
      parentRoute: typeof AuthenticatedUserSettingsProfileEditLayoutImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminLayoutRoute: typeof AuthenticatedAdminLayoutRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminLayoutRoute: AuthenticatedAdminLayoutRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppLayoutRouteChildren {
  AuthenticatedAppLayoutConnectorsRoute: typeof AuthenticatedAppLayoutConnectorsRoute
  AuthenticatedAppLayoutContactUsRoute: typeof AuthenticatedAppLayoutContactUsRoute
  AuthenticatedAppLayoutFeaturesRoute: typeof AuthenticatedAppLayoutFeaturesRoute
  AuthenticatedAppLayoutHowItWorksRoute: typeof AuthenticatedAppLayoutHowItWorksRoute
}

const AuthenticatedAppLayoutRouteChildren: AuthenticatedAppLayoutRouteChildren =
  {
    AuthenticatedAppLayoutConnectorsRoute:
      AuthenticatedAppLayoutConnectorsRoute,
    AuthenticatedAppLayoutContactUsRoute: AuthenticatedAppLayoutContactUsRoute,
    AuthenticatedAppLayoutFeaturesRoute: AuthenticatedAppLayoutFeaturesRoute,
    AuthenticatedAppLayoutHowItWorksRoute:
      AuthenticatedAppLayoutHowItWorksRoute,
  }

const AuthenticatedAppLayoutRouteWithChildren =
  AuthenticatedAppLayoutRoute._addFileChildren(
    AuthenticatedAppLayoutRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppLayoutRoute: typeof AuthenticatedAppLayoutRouteWithChildren
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppLayoutRoute: AuthenticatedAppLayoutRouteWithChildren,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedBlogLayoutRouteChildren {
  AuthenticatedBlogLayoutAboutRoute: typeof AuthenticatedBlogLayoutAboutRoute
  AuthenticatedBlogLayoutContactRoute: typeof AuthenticatedBlogLayoutContactRoute
}

const AuthenticatedBlogLayoutRouteChildren: AuthenticatedBlogLayoutRouteChildren =
  {
    AuthenticatedBlogLayoutAboutRoute: AuthenticatedBlogLayoutAboutRoute,
    AuthenticatedBlogLayoutContactRoute: AuthenticatedBlogLayoutContactRoute,
  }

const AuthenticatedBlogLayoutRouteWithChildren =
  AuthenticatedBlogLayoutRoute._addFileChildren(
    AuthenticatedBlogLayoutRouteChildren,
  )

interface AuthenticatedBlogRouteChildren {
  AuthenticatedBlogLayoutRoute: typeof AuthenticatedBlogLayoutRouteWithChildren
}

const AuthenticatedBlogRouteChildren: AuthenticatedBlogRouteChildren = {
  AuthenticatedBlogLayoutRoute: AuthenticatedBlogLayoutRouteWithChildren,
}

const AuthenticatedBlogRouteWithChildren =
  AuthenticatedBlogRoute._addFileChildren(AuthenticatedBlogRouteChildren)

interface AuthenticatedManagementsLayoutRouteChildren {
  AuthenticatedManagementsLayoutChatSupportRoute: typeof AuthenticatedManagementsLayoutChatSupportRoute
  AuthenticatedManagementsLayoutCloudRoute: typeof AuthenticatedManagementsLayoutCloudRoute
  AuthenticatedManagementsLayoutHomeRoute: typeof AuthenticatedManagementsLayoutHomeRoute
  AuthenticatedManagementsLayoutMeRoute: typeof AuthenticatedManagementsLayoutMeRoute
  AuthenticatedManagementsLayoutProjectsRoute: typeof AuthenticatedManagementsLayoutProjectsRoute
  AuthenticatedManagementsLayoutSpacesRoute: typeof AuthenticatedManagementsLayoutSpacesRoute
  AuthenticatedManagementsLayoutUsersRoute: typeof AuthenticatedManagementsLayoutUsersRoute
  AuthenticatedManagementsLayoutSubProjectsSubprojectidRoute: typeof AuthenticatedManagementsLayoutSubProjectsSubprojectidRoute
  AuthenticatedManagementsLayoutTeamsTeamIdRoute: typeof AuthenticatedManagementsLayoutTeamsTeamIdRoute
  AuthenticatedManagementsLayoutSubProjectsIndexRoute: typeof AuthenticatedManagementsLayoutSubProjectsIndexRoute
  AuthenticatedManagementsLayoutTeamsIndexRoute: typeof AuthenticatedManagementsLayoutTeamsIndexRoute
}

const AuthenticatedManagementsLayoutRouteChildren: AuthenticatedManagementsLayoutRouteChildren =
  {
    AuthenticatedManagementsLayoutChatSupportRoute:
      AuthenticatedManagementsLayoutChatSupportRoute,
    AuthenticatedManagementsLayoutCloudRoute:
      AuthenticatedManagementsLayoutCloudRoute,
    AuthenticatedManagementsLayoutHomeRoute:
      AuthenticatedManagementsLayoutHomeRoute,
    AuthenticatedManagementsLayoutMeRoute:
      AuthenticatedManagementsLayoutMeRoute,
    AuthenticatedManagementsLayoutProjectsRoute:
      AuthenticatedManagementsLayoutProjectsRoute,
    AuthenticatedManagementsLayoutSpacesRoute:
      AuthenticatedManagementsLayoutSpacesRoute,
    AuthenticatedManagementsLayoutUsersRoute:
      AuthenticatedManagementsLayoutUsersRoute,
    AuthenticatedManagementsLayoutSubProjectsSubprojectidRoute:
      AuthenticatedManagementsLayoutSubProjectsSubprojectidRoute,
    AuthenticatedManagementsLayoutTeamsTeamIdRoute:
      AuthenticatedManagementsLayoutTeamsTeamIdRoute,
    AuthenticatedManagementsLayoutSubProjectsIndexRoute:
      AuthenticatedManagementsLayoutSubProjectsIndexRoute,
    AuthenticatedManagementsLayoutTeamsIndexRoute:
      AuthenticatedManagementsLayoutTeamsIndexRoute,
  }

const AuthenticatedManagementsLayoutRouteWithChildren =
  AuthenticatedManagementsLayoutRoute._addFileChildren(
    AuthenticatedManagementsLayoutRouteChildren,
  )

interface AuthenticatedManagementsRouteChildren {
  AuthenticatedManagementsLayoutRoute: typeof AuthenticatedManagementsLayoutRouteWithChildren
}

const AuthenticatedManagementsRouteChildren: AuthenticatedManagementsRouteChildren =
  {
    AuthenticatedManagementsLayoutRoute:
      AuthenticatedManagementsLayoutRouteWithChildren,
  }

const AuthenticatedManagementsRouteWithChildren =
  AuthenticatedManagementsRoute._addFileChildren(
    AuthenticatedManagementsRouteChildren,
  )

interface AuthenticatedUserShowProfileLayoutRouteChildren {
  AuthenticatedUserShowProfileLayoutIdUserRoute: typeof AuthenticatedUserShowProfileLayoutIdUserRoute
  AuthenticatedUserShowProfileLayoutIndexRoute: typeof AuthenticatedUserShowProfileLayoutIndexRoute
}

const AuthenticatedUserShowProfileLayoutRouteChildren: AuthenticatedUserShowProfileLayoutRouteChildren =
  {
    AuthenticatedUserShowProfileLayoutIdUserRoute:
      AuthenticatedUserShowProfileLayoutIdUserRoute,
    AuthenticatedUserShowProfileLayoutIndexRoute:
      AuthenticatedUserShowProfileLayoutIndexRoute,
  }

const AuthenticatedUserShowProfileLayoutRouteWithChildren =
  AuthenticatedUserShowProfileLayoutRoute._addFileChildren(
    AuthenticatedUserShowProfileLayoutRouteChildren,
  )

interface AuthenticatedUserShowProfileRouteChildren {
  AuthenticatedUserShowProfileLayoutRoute: typeof AuthenticatedUserShowProfileLayoutRouteWithChildren
}

const AuthenticatedUserShowProfileRouteChildren: AuthenticatedUserShowProfileRouteChildren =
  {
    AuthenticatedUserShowProfileLayoutRoute:
      AuthenticatedUserShowProfileLayoutRouteWithChildren,
  }

const AuthenticatedUserShowProfileRouteWithChildren =
  AuthenticatedUserShowProfileRoute._addFileChildren(
    AuthenticatedUserShowProfileRouteChildren,
  )

interface AuthenticatedUserSettingsProfileEditLayoutRouteChildren {
  AuthenticatedUserSettingsProfileEditLayoutIdUserRoute: typeof AuthenticatedUserSettingsProfileEditLayoutIdUserRoute
}

const AuthenticatedUserSettingsProfileEditLayoutRouteChildren: AuthenticatedUserSettingsProfileEditLayoutRouteChildren =
  {
    AuthenticatedUserSettingsProfileEditLayoutIdUserRoute:
      AuthenticatedUserSettingsProfileEditLayoutIdUserRoute,
  }

const AuthenticatedUserSettingsProfileEditLayoutRouteWithChildren =
  AuthenticatedUserSettingsProfileEditLayoutRoute._addFileChildren(
    AuthenticatedUserSettingsProfileEditLayoutRouteChildren,
  )

interface AuthenticatedUserSettingsProfileEditRouteChildren {
  AuthenticatedUserSettingsProfileEditLayoutRoute: typeof AuthenticatedUserSettingsProfileEditLayoutRouteWithChildren
}

const AuthenticatedUserSettingsProfileEditRouteChildren: AuthenticatedUserSettingsProfileEditRouteChildren =
  {
    AuthenticatedUserSettingsProfileEditLayoutRoute:
      AuthenticatedUserSettingsProfileEditLayoutRouteWithChildren,
  }

const AuthenticatedUserSettingsProfileEditRouteWithChildren =
  AuthenticatedUserSettingsProfileEditRoute._addFileChildren(
    AuthenticatedUserSettingsProfileEditRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedContactUsRoute: typeof AuthenticatedContactUsRoute
  AuthenticatedFeaturesRoute: typeof AuthenticatedFeaturesRoute
  AuthenticatedHowItWorksRoute: typeof AuthenticatedHowItWorksRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedBimViewerUtIfcViewerSelectionRoute: typeof AuthenticatedBimViewerUtIfcViewerSelectionRoute
  AuthenticatedBimViewerUtGeometrySceneViewcubeRoute: typeof AuthenticatedBimViewerUtGeometrySceneViewcubeRoute
  AuthenticatedBimViewerUtIfcViewerSelectionFamilyRoute: typeof AuthenticatedBimViewerUtIfcViewerSelectionFamilyRoute
  AuthenticatedBimViewerUtViewCubeRoute: typeof AuthenticatedBimViewerUtViewCubeRoute
  AuthenticatedBimViewerUtWebglClippingCubeRoute: typeof AuthenticatedBimViewerUtWebglClippingCubeRoute
  AuthenticatedBimViewerUtWebglClippingStencilRoute: typeof AuthenticatedBimViewerUtWebglClippingStencilRoute
  AuthenticatedBimViewerUtWebglClippingStencilIfcRoute: typeof AuthenticatedBimViewerUtWebglClippingStencilIfcRoute
  AuthenticatedBimViewerUtWebglClippingV1Route: typeof AuthenticatedBimViewerUtWebglClippingV1Route
  AuthenticatedBimViewerUtWebglClippingV2Route: typeof AuthenticatedBimViewerUtWebglClippingV2Route
  AuthenticatedBlogRoute: typeof AuthenticatedBlogRouteWithChildren
  AuthenticatedManagementsRoute: typeof AuthenticatedManagementsRouteWithChildren
  AuthenticatedViewFileCodeRoute: typeof AuthenticatedViewFileCodeRoute
  AuthenticatedBimViewerUtIfcLoaderLazyRoute: typeof AuthenticatedBimViewerUtIfcLoaderLazyRoute
  AuthenticatedBimViewerUtInstancedMeshLazyRoute: typeof AuthenticatedBimViewerUtInstancedMeshLazyRoute
  AuthenticatedBimViewerUtViewerLazyRoute: typeof AuthenticatedBimViewerUtViewerLazyRoute
  AuthenticatedMyRoom3dIndexRoute: typeof AuthenticatedMyRoom3dIndexRoute
  AuthenticatedViewIndexRoute: typeof AuthenticatedViewIndexRoute
  AuthenticatedViewUploadIndexRoute: typeof AuthenticatedViewUploadIndexRoute
  AuthenticatedUserShowProfileRoute: typeof AuthenticatedUserShowProfileRouteWithChildren
  AuthenticatedUserShowCvIndexRoute: typeof AuthenticatedUserShowCvIndexRoute
  AuthenticatedUserShowPortfolioIndexRoute: typeof AuthenticatedUserShowPortfolioIndexRoute
  AuthenticatedUserSettingsProfileEditRoute: typeof AuthenticatedUserSettingsProfileEditRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedContactUsRoute: AuthenticatedContactUsRoute,
  AuthenticatedFeaturesRoute: AuthenticatedFeaturesRoute,
  AuthenticatedHowItWorksRoute: AuthenticatedHowItWorksRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedBimViewerUtIfcViewerSelectionRoute:
    AuthenticatedBimViewerUtIfcViewerSelectionRoute,
  AuthenticatedBimViewerUtGeometrySceneViewcubeRoute:
    AuthenticatedBimViewerUtGeometrySceneViewcubeRoute,
  AuthenticatedBimViewerUtIfcViewerSelectionFamilyRoute:
    AuthenticatedBimViewerUtIfcViewerSelectionFamilyRoute,
  AuthenticatedBimViewerUtViewCubeRoute: AuthenticatedBimViewerUtViewCubeRoute,
  AuthenticatedBimViewerUtWebglClippingCubeRoute:
    AuthenticatedBimViewerUtWebglClippingCubeRoute,
  AuthenticatedBimViewerUtWebglClippingStencilRoute:
    AuthenticatedBimViewerUtWebglClippingStencilRoute,
  AuthenticatedBimViewerUtWebglClippingStencilIfcRoute:
    AuthenticatedBimViewerUtWebglClippingStencilIfcRoute,
  AuthenticatedBimViewerUtWebglClippingV1Route:
    AuthenticatedBimViewerUtWebglClippingV1Route,
  AuthenticatedBimViewerUtWebglClippingV2Route:
    AuthenticatedBimViewerUtWebglClippingV2Route,
  AuthenticatedBlogRoute: AuthenticatedBlogRouteWithChildren,
  AuthenticatedManagementsRoute: AuthenticatedManagementsRouteWithChildren,
  AuthenticatedViewFileCodeRoute: AuthenticatedViewFileCodeRoute,
  AuthenticatedBimViewerUtIfcLoaderLazyRoute:
    AuthenticatedBimViewerUtIfcLoaderLazyRoute,
  AuthenticatedBimViewerUtInstancedMeshLazyRoute:
    AuthenticatedBimViewerUtInstancedMeshLazyRoute,
  AuthenticatedBimViewerUtViewerLazyRoute:
    AuthenticatedBimViewerUtViewerLazyRoute,
  AuthenticatedMyRoom3dIndexRoute: AuthenticatedMyRoom3dIndexRoute,
  AuthenticatedViewIndexRoute: AuthenticatedViewIndexRoute,
  AuthenticatedViewUploadIndexRoute: AuthenticatedViewUploadIndexRoute,
  AuthenticatedUserShowProfileRoute:
    AuthenticatedUserShowProfileRouteWithChildren,
  AuthenticatedUserShowCvIndexRoute: AuthenticatedUserShowCvIndexRoute,
  AuthenticatedUserShowPortfolioIndexRoute:
    AuthenticatedUserShowPortfolioIndexRoute,
  AuthenticatedUserSettingsProfileEditRoute:
    AuthenticatedUserSettingsProfileEditRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteRouteWithChildren
  '/500': typeof errors500LazyRoute
  '/callback': typeof authCallbackRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/contact-us': typeof AuthenticatedContactUsRoute
  '/features': typeof AuthenticatedFeaturesRoute
  '/how-it-works': typeof AuthenticatedHowItWorksRoute
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-in-2': typeof authSignIn2LazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/503': typeof errors503LazyRoute
  '/admin': typeof AuthenticatedAdminLayoutRoute
  '/app': typeof AuthenticatedAppLayoutRouteWithChildren
  '/bim-viewer-ut/Ifc-viewer-selection': typeof AuthenticatedBimViewerUtIfcViewerSelectionRoute
  '/bim-viewer-ut/geometry-scene-viewcube': typeof AuthenticatedBimViewerUtGeometrySceneViewcubeRoute
  '/bim-viewer-ut/ifc-viewer-selection-family': typeof AuthenticatedBimViewerUtIfcViewerSelectionFamilyRoute
  '/bim-viewer-ut/view-cube': typeof AuthenticatedBimViewerUtViewCubeRoute
  '/bim-viewer-ut/webgl-clipping-cube': typeof AuthenticatedBimViewerUtWebglClippingCubeRoute
  '/bim-viewer-ut/webgl-clipping-stencil': typeof AuthenticatedBimViewerUtWebglClippingStencilRoute
  '/bim-viewer-ut/webgl-clipping-stencil-ifc': typeof AuthenticatedBimViewerUtWebglClippingStencilIfcRoute
  '/bim-viewer-ut/webgl-clipping-v1': typeof AuthenticatedBimViewerUtWebglClippingV1Route
  '/bim-viewer-ut/webgl-clipping-v2': typeof AuthenticatedBimViewerUtWebglClippingV2Route
  '/blog': typeof AuthenticatedBlogLayoutRouteWithChildren
  '/managements': typeof AuthenticatedManagementsLayoutRouteWithChildren
  '/view/$fileCode': typeof AuthenticatedViewFileCodeRoute
  '/bim-viewer-ut/ifc-loader': typeof AuthenticatedBimViewerUtIfcLoaderLazyRoute
  '/bim-viewer-ut/instanced-mesh': typeof AuthenticatedBimViewerUtInstancedMeshLazyRoute
  '/bim-viewer-ut/viewer': typeof AuthenticatedBimViewerUtViewerLazyRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/my-room-3d': typeof AuthenticatedMyRoom3dIndexRoute
  '/view': typeof AuthenticatedViewIndexRoute
  '/example-model/ifc': typeof ExampleModelIfcIndexRoute
  '/app/connectors': typeof AuthenticatedAppLayoutConnectorsRoute
  '/app/contact-us': typeof AuthenticatedAppLayoutContactUsRoute
  '/app/features': typeof AuthenticatedAppLayoutFeaturesRoute
  '/app/how-it-works': typeof AuthenticatedAppLayoutHowItWorksRoute
  '/blog/about': typeof AuthenticatedBlogLayoutAboutRoute
  '/blog/contact': typeof AuthenticatedBlogLayoutContactRoute
  '/managements/chat-support': typeof AuthenticatedManagementsLayoutChatSupportRoute
  '/managements/cloud': typeof AuthenticatedManagementsLayoutCloudRoute
  '/managements/home': typeof AuthenticatedManagementsLayoutHomeRoute
  '/managements/me': typeof AuthenticatedManagementsLayoutMeRoute
  '/managements/projects': typeof AuthenticatedManagementsLayoutProjectsRoute
  '/managements/spaces': typeof AuthenticatedManagementsLayoutSpacesRoute
  '/managements/users': typeof AuthenticatedManagementsLayoutUsersRoute
  '/view/upload': typeof AuthenticatedViewUploadIndexRoute
  '/managements/sub-projects/$sub_project_id': typeof AuthenticatedManagementsLayoutSubProjectsSubprojectidRoute
  '/managements/teams/$teamId': typeof AuthenticatedManagementsLayoutTeamsTeamIdRoute
  '/user/show/profile': typeof AuthenticatedUserShowProfileLayoutRouteWithChildren
  '/managements/sub-projects': typeof AuthenticatedManagementsLayoutSubProjectsIndexRoute
  '/managements/teams': typeof AuthenticatedManagementsLayoutTeamsIndexRoute
  '/user/show/cv': typeof AuthenticatedUserShowCvIndexRoute
  '/user/show/portfolio': typeof AuthenticatedUserShowPortfolioIndexRoute
  '/user/settings/profile/edit': typeof AuthenticatedUserSettingsProfileEditLayoutRouteWithChildren
  '/user/show/profile/$idUser': typeof AuthenticatedUserShowProfileLayoutIdUserRoute
  '/user/show/profile/': typeof AuthenticatedUserShowProfileLayoutIndexRoute
  '/user/settings/profile/edit/$idUser': typeof AuthenticatedUserSettingsProfileEditLayoutIdUserRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteRouteWithChildren
  '/500': typeof errors500LazyRoute
  '/callback': typeof authCallbackRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/contact-us': typeof AuthenticatedContactUsRoute
  '/features': typeof AuthenticatedFeaturesRoute
  '/how-it-works': typeof AuthenticatedHowItWorksRoute
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-in-2': typeof authSignIn2LazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/503': typeof errors503LazyRoute
  '/admin': typeof AuthenticatedAdminLayoutRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/bim-viewer-ut/Ifc-viewer-selection': typeof AuthenticatedBimViewerUtIfcViewerSelectionRoute
  '/bim-viewer-ut/geometry-scene-viewcube': typeof AuthenticatedBimViewerUtGeometrySceneViewcubeRoute
  '/bim-viewer-ut/ifc-viewer-selection-family': typeof AuthenticatedBimViewerUtIfcViewerSelectionFamilyRoute
  '/bim-viewer-ut/view-cube': typeof AuthenticatedBimViewerUtViewCubeRoute
  '/bim-viewer-ut/webgl-clipping-cube': typeof AuthenticatedBimViewerUtWebglClippingCubeRoute
  '/bim-viewer-ut/webgl-clipping-stencil': typeof AuthenticatedBimViewerUtWebglClippingStencilRoute
  '/bim-viewer-ut/webgl-clipping-stencil-ifc': typeof AuthenticatedBimViewerUtWebglClippingStencilIfcRoute
  '/bim-viewer-ut/webgl-clipping-v1': typeof AuthenticatedBimViewerUtWebglClippingV1Route
  '/bim-viewer-ut/webgl-clipping-v2': typeof AuthenticatedBimViewerUtWebglClippingV2Route
  '/blog': typeof AuthenticatedBlogLayoutRouteWithChildren
  '/managements': typeof AuthenticatedManagementsLayoutRouteWithChildren
  '/view/$fileCode': typeof AuthenticatedViewFileCodeRoute
  '/bim-viewer-ut/ifc-loader': typeof AuthenticatedBimViewerUtIfcLoaderLazyRoute
  '/bim-viewer-ut/instanced-mesh': typeof AuthenticatedBimViewerUtInstancedMeshLazyRoute
  '/bim-viewer-ut/viewer': typeof AuthenticatedBimViewerUtViewerLazyRoute
  '/my-room-3d': typeof AuthenticatedMyRoom3dIndexRoute
  '/view': typeof AuthenticatedViewIndexRoute
  '/example-model/ifc': typeof ExampleModelIfcIndexRoute
  '/app/connectors': typeof AuthenticatedAppLayoutConnectorsRoute
  '/app/contact-us': typeof AuthenticatedAppLayoutContactUsRoute
  '/app/features': typeof AuthenticatedAppLayoutFeaturesRoute
  '/app/how-it-works': typeof AuthenticatedAppLayoutHowItWorksRoute
  '/blog/about': typeof AuthenticatedBlogLayoutAboutRoute
  '/blog/contact': typeof AuthenticatedBlogLayoutContactRoute
  '/managements/chat-support': typeof AuthenticatedManagementsLayoutChatSupportRoute
  '/managements/cloud': typeof AuthenticatedManagementsLayoutCloudRoute
  '/managements/home': typeof AuthenticatedManagementsLayoutHomeRoute
  '/managements/me': typeof AuthenticatedManagementsLayoutMeRoute
  '/managements/projects': typeof AuthenticatedManagementsLayoutProjectsRoute
  '/managements/spaces': typeof AuthenticatedManagementsLayoutSpacesRoute
  '/managements/users': typeof AuthenticatedManagementsLayoutUsersRoute
  '/view/upload': typeof AuthenticatedViewUploadIndexRoute
  '/managements/sub-projects/$sub_project_id': typeof AuthenticatedManagementsLayoutSubProjectsSubprojectidRoute
  '/managements/teams/$teamId': typeof AuthenticatedManagementsLayoutTeamsTeamIdRoute
  '/user/show/profile': typeof AuthenticatedUserShowProfileLayoutIndexRoute
  '/managements/sub-projects': typeof AuthenticatedManagementsLayoutSubProjectsIndexRoute
  '/managements/teams': typeof AuthenticatedManagementsLayoutTeamsIndexRoute
  '/user/show/cv': typeof AuthenticatedUserShowCvIndexRoute
  '/user/show/portfolio': typeof AuthenticatedUserShowPortfolioIndexRoute
  '/user/settings/profile/edit': typeof AuthenticatedUserSettingsProfileEditLayoutRouteWithChildren
  '/user/show/profile/$idUser': typeof AuthenticatedUserShowProfileLayoutIdUserRoute
  '/user/settings/profile/edit/$idUser': typeof AuthenticatedUserSettingsProfileEditLayoutIdUserRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/500': typeof auth500Route
  '/(auth)/callback': typeof authCallbackRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/_authenticated/contact-us': typeof AuthenticatedContactUsRoute
  '/_authenticated/features': typeof AuthenticatedFeaturesRoute
  '/_authenticated/how-it-works': typeof AuthenticatedHowItWorksRoute
  '/(auth)/forgot-password': typeof authForgotPasswordLazyRoute
  '/(auth)/sign-in-2': typeof authSignIn2LazyRoute
  '/(auth)/sign-up': typeof authSignUpLazyRoute
  '/(errors)/401': typeof errors401LazyRoute
  '/(errors)/403': typeof errors403LazyRoute
  '/(errors)/404': typeof errors404LazyRoute
  '/(errors)/500': typeof errors500LazyRoute
  '/(errors)/503': typeof errors503LazyRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/admin/_layout': typeof AuthenticatedAdminLayoutRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/_layout': typeof AuthenticatedAppLayoutRouteWithChildren
  '/_authenticated/bim-viewer-ut/Ifc-viewer-selection': typeof AuthenticatedBimViewerUtIfcViewerSelectionRoute
  '/_authenticated/bim-viewer-ut/geometry-scene-viewcube': typeof AuthenticatedBimViewerUtGeometrySceneViewcubeRoute
  '/_authenticated/bim-viewer-ut/ifc-viewer-selection-family': typeof AuthenticatedBimViewerUtIfcViewerSelectionFamilyRoute
  '/_authenticated/bim-viewer-ut/view-cube': typeof AuthenticatedBimViewerUtViewCubeRoute
  '/_authenticated/bim-viewer-ut/webgl-clipping-cube': typeof AuthenticatedBimViewerUtWebglClippingCubeRoute
  '/_authenticated/bim-viewer-ut/webgl-clipping-stencil': typeof AuthenticatedBimViewerUtWebglClippingStencilRoute
  '/_authenticated/bim-viewer-ut/webgl-clipping-stencil-ifc': typeof AuthenticatedBimViewerUtWebglClippingStencilIfcRoute
  '/_authenticated/bim-viewer-ut/webgl-clipping-v1': typeof AuthenticatedBimViewerUtWebglClippingV1Route
  '/_authenticated/bim-viewer-ut/webgl-clipping-v2': typeof AuthenticatedBimViewerUtWebglClippingV2Route
  '/_authenticated/blog': typeof AuthenticatedBlogRouteWithChildren
  '/_authenticated/blog/_layout': typeof AuthenticatedBlogLayoutRouteWithChildren
  '/_authenticated/managements': typeof AuthenticatedManagementsRouteWithChildren
  '/_authenticated/managements/_layout': typeof AuthenticatedManagementsLayoutRouteWithChildren
  '/_authenticated/view/$fileCode': typeof AuthenticatedViewFileCodeRoute
  '/_authenticated/bim-viewer-ut/ifc-loader': typeof AuthenticatedBimViewerUtIfcLoaderLazyRoute
  '/_authenticated/bim-viewer-ut/instanced-mesh': typeof AuthenticatedBimViewerUtInstancedMeshLazyRoute
  '/_authenticated/bim-viewer-ut/viewer': typeof AuthenticatedBimViewerUtViewerLazyRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/my-room-3d/': typeof AuthenticatedMyRoom3dIndexRoute
  '/_authenticated/view/': typeof AuthenticatedViewIndexRoute
  '/example-model/ifc/': typeof ExampleModelIfcIndexRoute
  '/_authenticated/app/_layout/connectors': typeof AuthenticatedAppLayoutConnectorsRoute
  '/_authenticated/app/_layout/contact-us': typeof AuthenticatedAppLayoutContactUsRoute
  '/_authenticated/app/_layout/features': typeof AuthenticatedAppLayoutFeaturesRoute
  '/_authenticated/app/_layout/how-it-works': typeof AuthenticatedAppLayoutHowItWorksRoute
  '/_authenticated/blog/_layout/about': typeof AuthenticatedBlogLayoutAboutRoute
  '/_authenticated/blog/_layout/contact': typeof AuthenticatedBlogLayoutContactRoute
  '/_authenticated/managements/_layout/chat-support': typeof AuthenticatedManagementsLayoutChatSupportRoute
  '/_authenticated/managements/_layout/cloud': typeof AuthenticatedManagementsLayoutCloudRoute
  '/_authenticated/managements/_layout/home': typeof AuthenticatedManagementsLayoutHomeRoute
  '/_authenticated/managements/_layout/me': typeof AuthenticatedManagementsLayoutMeRoute
  '/_authenticated/managements/_layout/projects': typeof AuthenticatedManagementsLayoutProjectsRoute
  '/_authenticated/managements/_layout/spaces': typeof AuthenticatedManagementsLayoutSpacesRoute
  '/_authenticated/managements/_layout/users': typeof AuthenticatedManagementsLayoutUsersRoute
  '/_authenticated/view/upload/': typeof AuthenticatedViewUploadIndexRoute
  '/_authenticated/managements/_layout/sub-projects/$sub_project_id': typeof AuthenticatedManagementsLayoutSubProjectsSubprojectidRoute
  '/_authenticated/managements/_layout/teams/$teamId': typeof AuthenticatedManagementsLayoutTeamsTeamIdRoute
  '/_authenticated/user/show/profile': typeof AuthenticatedUserShowProfileRouteWithChildren
  '/_authenticated/user/show/profile/_layout': typeof AuthenticatedUserShowProfileLayoutRouteWithChildren
  '/_authenticated/managements/_layout/sub-projects/': typeof AuthenticatedManagementsLayoutSubProjectsIndexRoute
  '/_authenticated/managements/_layout/teams/': typeof AuthenticatedManagementsLayoutTeamsIndexRoute
  '/_authenticated/user/show/cv/': typeof AuthenticatedUserShowCvIndexRoute
  '/_authenticated/user/show/portfolio/': typeof AuthenticatedUserShowPortfolioIndexRoute
  '/_authenticated/user/settings/profile/edit': typeof AuthenticatedUserSettingsProfileEditRouteWithChildren
  '/_authenticated/user/settings/profile/edit/_layout': typeof AuthenticatedUserSettingsProfileEditLayoutRouteWithChildren
  '/_authenticated/user/show/profile/_layout/$idUser': typeof AuthenticatedUserShowProfileLayoutIdUserRoute
  '/_authenticated/user/show/profile/_layout/': typeof AuthenticatedUserShowProfileLayoutIndexRoute
  '/_authenticated/user/settings/profile/edit/_layout/$idUser': typeof AuthenticatedUserSettingsProfileEditLayoutIdUserRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/500'
    | '/callback'
    | '/reset-password'
    | '/sign-in'
    | '/verify-email'
    | '/contact-us'
    | '/features'
    | '/how-it-works'
    | '/forgot-password'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/503'
    | '/admin'
    | '/app'
    | '/bim-viewer-ut/Ifc-viewer-selection'
    | '/bim-viewer-ut/geometry-scene-viewcube'
    | '/bim-viewer-ut/ifc-viewer-selection-family'
    | '/bim-viewer-ut/view-cube'
    | '/bim-viewer-ut/webgl-clipping-cube'
    | '/bim-viewer-ut/webgl-clipping-stencil'
    | '/bim-viewer-ut/webgl-clipping-stencil-ifc'
    | '/bim-viewer-ut/webgl-clipping-v1'
    | '/bim-viewer-ut/webgl-clipping-v2'
    | '/blog'
    | '/managements'
    | '/view/$fileCode'
    | '/bim-viewer-ut/ifc-loader'
    | '/bim-viewer-ut/instanced-mesh'
    | '/bim-viewer-ut/viewer'
    | '/app/'
    | '/my-room-3d'
    | '/view'
    | '/example-model/ifc'
    | '/app/connectors'
    | '/app/contact-us'
    | '/app/features'
    | '/app/how-it-works'
    | '/blog/about'
    | '/blog/contact'
    | '/managements/chat-support'
    | '/managements/cloud'
    | '/managements/home'
    | '/managements/me'
    | '/managements/projects'
    | '/managements/spaces'
    | '/managements/users'
    | '/view/upload'
    | '/managements/sub-projects/$sub_project_id'
    | '/managements/teams/$teamId'
    | '/user/show/profile'
    | '/managements/sub-projects'
    | '/managements/teams'
    | '/user/show/cv'
    | '/user/show/portfolio'
    | '/user/settings/profile/edit'
    | '/user/show/profile/$idUser'
    | '/user/show/profile/'
    | '/user/settings/profile/edit/$idUser'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/500'
    | '/callback'
    | '/reset-password'
    | '/sign-in'
    | '/verify-email'
    | '/contact-us'
    | '/features'
    | '/how-it-works'
    | '/forgot-password'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/503'
    | '/admin'
    | '/app'
    | '/bim-viewer-ut/Ifc-viewer-selection'
    | '/bim-viewer-ut/geometry-scene-viewcube'
    | '/bim-viewer-ut/ifc-viewer-selection-family'
    | '/bim-viewer-ut/view-cube'
    | '/bim-viewer-ut/webgl-clipping-cube'
    | '/bim-viewer-ut/webgl-clipping-stencil'
    | '/bim-viewer-ut/webgl-clipping-stencil-ifc'
    | '/bim-viewer-ut/webgl-clipping-v1'
    | '/bim-viewer-ut/webgl-clipping-v2'
    | '/blog'
    | '/managements'
    | '/view/$fileCode'
    | '/bim-viewer-ut/ifc-loader'
    | '/bim-viewer-ut/instanced-mesh'
    | '/bim-viewer-ut/viewer'
    | '/my-room-3d'
    | '/view'
    | '/example-model/ifc'
    | '/app/connectors'
    | '/app/contact-us'
    | '/app/features'
    | '/app/how-it-works'
    | '/blog/about'
    | '/blog/contact'
    | '/managements/chat-support'
    | '/managements/cloud'
    | '/managements/home'
    | '/managements/me'
    | '/managements/projects'
    | '/managements/spaces'
    | '/managements/users'
    | '/view/upload'
    | '/managements/sub-projects/$sub_project_id'
    | '/managements/teams/$teamId'
    | '/user/show/profile'
    | '/managements/sub-projects'
    | '/managements/teams'
    | '/user/show/cv'
    | '/user/show/portfolio'
    | '/user/settings/profile/edit'
    | '/user/show/profile/$idUser'
    | '/user/settings/profile/edit/$idUser'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/(auth)/500'
    | '/(auth)/callback'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/verify-email'
    | '/_authenticated/contact-us'
    | '/_authenticated/features'
    | '/_authenticated/how-it-works'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/admin'
    | '/_authenticated/admin/_layout'
    | '/_authenticated/app'
    | '/_authenticated/app/_layout'
    | '/_authenticated/bim-viewer-ut/Ifc-viewer-selection'
    | '/_authenticated/bim-viewer-ut/geometry-scene-viewcube'
    | '/_authenticated/bim-viewer-ut/ifc-viewer-selection-family'
    | '/_authenticated/bim-viewer-ut/view-cube'
    | '/_authenticated/bim-viewer-ut/webgl-clipping-cube'
    | '/_authenticated/bim-viewer-ut/webgl-clipping-stencil'
    | '/_authenticated/bim-viewer-ut/webgl-clipping-stencil-ifc'
    | '/_authenticated/bim-viewer-ut/webgl-clipping-v1'
    | '/_authenticated/bim-viewer-ut/webgl-clipping-v2'
    | '/_authenticated/blog'
    | '/_authenticated/blog/_layout'
    | '/_authenticated/managements'
    | '/_authenticated/managements/_layout'
    | '/_authenticated/view/$fileCode'
    | '/_authenticated/bim-viewer-ut/ifc-loader'
    | '/_authenticated/bim-viewer-ut/instanced-mesh'
    | '/_authenticated/bim-viewer-ut/viewer'
    | '/_authenticated/app/'
    | '/_authenticated/my-room-3d/'
    | '/_authenticated/view/'
    | '/example-model/ifc/'
    | '/_authenticated/app/_layout/connectors'
    | '/_authenticated/app/_layout/contact-us'
    | '/_authenticated/app/_layout/features'
    | '/_authenticated/app/_layout/how-it-works'
    | '/_authenticated/blog/_layout/about'
    | '/_authenticated/blog/_layout/contact'
    | '/_authenticated/managements/_layout/chat-support'
    | '/_authenticated/managements/_layout/cloud'
    | '/_authenticated/managements/_layout/home'
    | '/_authenticated/managements/_layout/me'
    | '/_authenticated/managements/_layout/projects'
    | '/_authenticated/managements/_layout/spaces'
    | '/_authenticated/managements/_layout/users'
    | '/_authenticated/view/upload/'
    | '/_authenticated/managements/_layout/sub-projects/$sub_project_id'
    | '/_authenticated/managements/_layout/teams/$teamId'
    | '/_authenticated/user/show/profile'
    | '/_authenticated/user/show/profile/_layout'
    | '/_authenticated/managements/_layout/sub-projects/'
    | '/_authenticated/managements/_layout/teams/'
    | '/_authenticated/user/show/cv/'
    | '/_authenticated/user/show/portfolio/'
    | '/_authenticated/user/settings/profile/edit'
    | '/_authenticated/user/settings/profile/edit/_layout'
    | '/_authenticated/user/show/profile/_layout/$idUser'
    | '/_authenticated/user/show/profile/_layout/'
    | '/_authenticated/user/settings/profile/edit/_layout/$idUser'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  auth500Route: typeof auth500Route
  authCallbackRoute: typeof authCallbackRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
  authForgotPasswordLazyRoute: typeof authForgotPasswordLazyRoute
  authSignIn2LazyRoute: typeof authSignIn2LazyRoute
  authSignUpLazyRoute: typeof authSignUpLazyRoute
  errors401LazyRoute: typeof errors401LazyRoute
  errors403LazyRoute: typeof errors403LazyRoute
  errors404LazyRoute: typeof errors404LazyRoute
  errors500LazyRoute: typeof errors500LazyRoute
  errors503LazyRoute: typeof errors503LazyRoute
  ExampleModelIfcIndexRoute: typeof ExampleModelIfcIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  auth500Route: auth500Route,
  authCallbackRoute: authCallbackRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
  authForgotPasswordLazyRoute: authForgotPasswordLazyRoute,
  authSignIn2LazyRoute: authSignIn2LazyRoute,
  authSignUpLazyRoute: authSignUpLazyRoute,
  errors401LazyRoute: errors401LazyRoute,
  errors403LazyRoute: errors403LazyRoute,
  errors404LazyRoute: errors404LazyRoute,
  errors500LazyRoute: errors500LazyRoute,
  errors503LazyRoute: errors503LazyRoute,
  ExampleModelIfcIndexRoute: ExampleModelIfcIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/(auth)/500",
        "/(auth)/callback",
        "/(auth)/reset-password",
        "/(auth)/sign-in",
        "/(auth)/verify-email",
        "/(auth)/forgot-password",
        "/(auth)/sign-in-2",
        "/(auth)/sign-up",
        "/(errors)/401",
        "/(errors)/403",
        "/(errors)/404",
        "/(errors)/500",
        "/(errors)/503",
        "/example-model/ifc/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/contact-us",
        "/_authenticated/features",
        "/_authenticated/how-it-works",
        "/_authenticated/admin",
        "/_authenticated/app",
        "/_authenticated/bim-viewer-ut/Ifc-viewer-selection",
        "/_authenticated/bim-viewer-ut/geometry-scene-viewcube",
        "/_authenticated/bim-viewer-ut/ifc-viewer-selection-family",
        "/_authenticated/bim-viewer-ut/view-cube",
        "/_authenticated/bim-viewer-ut/webgl-clipping-cube",
        "/_authenticated/bim-viewer-ut/webgl-clipping-stencil",
        "/_authenticated/bim-viewer-ut/webgl-clipping-stencil-ifc",
        "/_authenticated/bim-viewer-ut/webgl-clipping-v1",
        "/_authenticated/bim-viewer-ut/webgl-clipping-v2",
        "/_authenticated/blog",
        "/_authenticated/managements",
        "/_authenticated/view/$fileCode",
        "/_authenticated/bim-viewer-ut/ifc-loader",
        "/_authenticated/bim-viewer-ut/instanced-mesh",
        "/_authenticated/bim-viewer-ut/viewer",
        "/_authenticated/my-room-3d/",
        "/_authenticated/view/",
        "/_authenticated/view/upload/",
        "/_authenticated/user/show/profile",
        "/_authenticated/user/show/cv/",
        "/_authenticated/user/show/portfolio/",
        "/_authenticated/user/settings/profile/edit"
      ]
    },
    "/(auth)/500": {
      "filePath": "(auth)/500.tsx"
    },
    "/(auth)/callback": {
      "filePath": "(auth)/callback.tsx"
    },
    "/(auth)/reset-password": {
      "filePath": "(auth)/reset-password.tsx"
    },
    "/(auth)/sign-in": {
      "filePath": "(auth)/sign-in.tsx"
    },
    "/(auth)/verify-email": {
      "filePath": "(auth)/verify-email.tsx"
    },
    "/_authenticated/contact-us": {
      "filePath": "_authenticated/contact-us.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/features": {
      "filePath": "_authenticated/features.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/how-it-works": {
      "filePath": "_authenticated/how-it-works.tsx",
      "parent": "/_authenticated"
    },
    "/(auth)/forgot-password": {
      "filePath": "(auth)/forgot-password.lazy.tsx"
    },
    "/(auth)/sign-in-2": {
      "filePath": "(auth)/sign-in-2.lazy.tsx"
    },
    "/(auth)/sign-up": {
      "filePath": "(auth)/sign-up.lazy.tsx"
    },
    "/(errors)/401": {
      "filePath": "(errors)/401.lazy.tsx"
    },
    "/(errors)/403": {
      "filePath": "(errors)/403.lazy.tsx"
    },
    "/(errors)/404": {
      "filePath": "(errors)/404.lazy.tsx"
    },
    "/(errors)/500": {
      "filePath": "(errors)/500.lazy.tsx"
    },
    "/(errors)/503": {
      "filePath": "(errors)/503.lazy.tsx"
    },
    "/_authenticated/admin": {
      "filePath": "_authenticated/admin",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/admin/_layout"
      ]
    },
    "/_authenticated/admin/_layout": {
      "filePath": "_authenticated/admin/_layout.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/app": {
      "filePath": "_authenticated/app",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/app/_layout",
        "/_authenticated/app/"
      ]
    },
    "/_authenticated/app/_layout": {
      "filePath": "_authenticated/app/_layout.tsx",
      "parent": "/_authenticated/app",
      "children": [
        "/_authenticated/app/_layout/connectors",
        "/_authenticated/app/_layout/contact-us",
        "/_authenticated/app/_layout/features",
        "/_authenticated/app/_layout/how-it-works"
      ]
    },
    "/_authenticated/bim-viewer-ut/Ifc-viewer-selection": {
      "filePath": "_authenticated/bim-viewer-ut/Ifc-viewer-selection.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/bim-viewer-ut/geometry-scene-viewcube": {
      "filePath": "_authenticated/bim-viewer-ut/geometry-scene-viewcube.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/bim-viewer-ut/ifc-viewer-selection-family": {
      "filePath": "_authenticated/bim-viewer-ut/ifc-viewer-selection-family.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/bim-viewer-ut/view-cube": {
      "filePath": "_authenticated/bim-viewer-ut/view-cube.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/bim-viewer-ut/webgl-clipping-cube": {
      "filePath": "_authenticated/bim-viewer-ut/webgl-clipping-cube.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/bim-viewer-ut/webgl-clipping-stencil": {
      "filePath": "_authenticated/bim-viewer-ut/webgl-clipping-stencil.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/bim-viewer-ut/webgl-clipping-stencil-ifc": {
      "filePath": "_authenticated/bim-viewer-ut/webgl-clipping-stencil-ifc.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/bim-viewer-ut/webgl-clipping-v1": {
      "filePath": "_authenticated/bim-viewer-ut/webgl-clipping-v1.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/bim-viewer-ut/webgl-clipping-v2": {
      "filePath": "_authenticated/bim-viewer-ut/webgl-clipping-v2.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/blog": {
      "filePath": "_authenticated/blog",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/blog/_layout"
      ]
    },
    "/_authenticated/blog/_layout": {
      "filePath": "_authenticated/blog/_layout.tsx",
      "parent": "/_authenticated/blog",
      "children": [
        "/_authenticated/blog/_layout/about",
        "/_authenticated/blog/_layout/contact"
      ]
    },
    "/_authenticated/managements": {
      "filePath": "_authenticated/managements",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/managements/_layout"
      ]
    },
    "/_authenticated/managements/_layout": {
      "filePath": "_authenticated/managements/_layout.tsx",
      "parent": "/_authenticated/managements",
      "children": [
        "/_authenticated/managements/_layout/chat-support",
        "/_authenticated/managements/_layout/cloud",
        "/_authenticated/managements/_layout/home",
        "/_authenticated/managements/_layout/me",
        "/_authenticated/managements/_layout/projects",
        "/_authenticated/managements/_layout/spaces",
        "/_authenticated/managements/_layout/users",
        "/_authenticated/managements/_layout/sub-projects/$sub_project_id",
        "/_authenticated/managements/_layout/teams/$teamId",
        "/_authenticated/managements/_layout/sub-projects/",
        "/_authenticated/managements/_layout/teams/"
      ]
    },
    "/_authenticated/view/$fileCode": {
      "filePath": "_authenticated/view/$fileCode.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/bim-viewer-ut/ifc-loader": {
      "filePath": "_authenticated/bim-viewer-ut/ifc-loader.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/bim-viewer-ut/instanced-mesh": {
      "filePath": "_authenticated/bim-viewer-ut/instanced-mesh.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/bim-viewer-ut/viewer": {
      "filePath": "_authenticated/bim-viewer-ut/viewer.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/app/": {
      "filePath": "_authenticated/app/index.tsx",
      "parent": "/_authenticated/app"
    },
    "/_authenticated/my-room-3d/": {
      "filePath": "_authenticated/my-room-3d/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/view/": {
      "filePath": "_authenticated/view/index.tsx",
      "parent": "/_authenticated"
    },
    "/example-model/ifc/": {
      "filePath": "example-model/ifc/index.ts"
    },
    "/_authenticated/app/_layout/connectors": {
      "filePath": "_authenticated/app/_layout/connectors.tsx",
      "parent": "/_authenticated/app/_layout"
    },
    "/_authenticated/app/_layout/contact-us": {
      "filePath": "_authenticated/app/_layout/contact-us.tsx",
      "parent": "/_authenticated/app/_layout"
    },
    "/_authenticated/app/_layout/features": {
      "filePath": "_authenticated/app/_layout/features.tsx",
      "parent": "/_authenticated/app/_layout"
    },
    "/_authenticated/app/_layout/how-it-works": {
      "filePath": "_authenticated/app/_layout/how-it-works.tsx",
      "parent": "/_authenticated/app/_layout"
    },
    "/_authenticated/blog/_layout/about": {
      "filePath": "_authenticated/blog/_layout/about.tsx",
      "parent": "/_authenticated/blog/_layout"
    },
    "/_authenticated/blog/_layout/contact": {
      "filePath": "_authenticated/blog/_layout/contact.tsx",
      "parent": "/_authenticated/blog/_layout"
    },
    "/_authenticated/managements/_layout/chat-support": {
      "filePath": "_authenticated/managements/_layout/chat-support.tsx",
      "parent": "/_authenticated/managements/_layout"
    },
    "/_authenticated/managements/_layout/cloud": {
      "filePath": "_authenticated/managements/_layout/cloud.tsx",
      "parent": "/_authenticated/managements/_layout"
    },
    "/_authenticated/managements/_layout/home": {
      "filePath": "_authenticated/managements/_layout/home.tsx",
      "parent": "/_authenticated/managements/_layout"
    },
    "/_authenticated/managements/_layout/me": {
      "filePath": "_authenticated/managements/_layout/me.tsx",
      "parent": "/_authenticated/managements/_layout"
    },
    "/_authenticated/managements/_layout/projects": {
      "filePath": "_authenticated/managements/_layout/projects.tsx",
      "parent": "/_authenticated/managements/_layout"
    },
    "/_authenticated/managements/_layout/spaces": {
      "filePath": "_authenticated/managements/_layout/spaces.tsx",
      "parent": "/_authenticated/managements/_layout"
    },
    "/_authenticated/managements/_layout/users": {
      "filePath": "_authenticated/managements/_layout/users.tsx",
      "parent": "/_authenticated/managements/_layout"
    },
    "/_authenticated/view/upload/": {
      "filePath": "_authenticated/view/upload/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/managements/_layout/sub-projects/$sub_project_id": {
      "filePath": "_authenticated/managements/_layout/sub-projects/$sub_project_id.tsx",
      "parent": "/_authenticated/managements/_layout"
    },
    "/_authenticated/managements/_layout/teams/$teamId": {
      "filePath": "_authenticated/managements/_layout/teams/$teamId.tsx",
      "parent": "/_authenticated/managements/_layout"
    },
    "/_authenticated/user/show/profile": {
      "filePath": "_authenticated/user/show/profile",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/user/show/profile/_layout"
      ]
    },
    "/_authenticated/user/show/profile/_layout": {
      "filePath": "_authenticated/user/show/profile/_layout.tsx",
      "parent": "/_authenticated/user/show/profile",
      "children": [
        "/_authenticated/user/show/profile/_layout/$idUser",
        "/_authenticated/user/show/profile/_layout/"
      ]
    },
    "/_authenticated/managements/_layout/sub-projects/": {
      "filePath": "_authenticated/managements/_layout/sub-projects/index.tsx",
      "parent": "/_authenticated/managements/_layout"
    },
    "/_authenticated/managements/_layout/teams/": {
      "filePath": "_authenticated/managements/_layout/teams/index.tsx",
      "parent": "/_authenticated/managements/_layout"
    },
    "/_authenticated/user/show/cv/": {
      "filePath": "_authenticated/user/show/cv/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/user/show/portfolio/": {
      "filePath": "_authenticated/user/show/portfolio/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/user/settings/profile/edit": {
      "filePath": "_authenticated/user/settings/profile/edit",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/user/settings/profile/edit/_layout"
      ]
    },
    "/_authenticated/user/settings/profile/edit/_layout": {
      "filePath": "_authenticated/user/settings/profile/edit/_layout.tsx",
      "parent": "/_authenticated/user/settings/profile/edit",
      "children": [
        "/_authenticated/user/settings/profile/edit/_layout/$idUser"
      ]
    },
    "/_authenticated/user/show/profile/_layout/$idUser": {
      "filePath": "_authenticated/user/show/profile/_layout/$idUser.tsx",
      "parent": "/_authenticated/user/show/profile/_layout"
    },
    "/_authenticated/user/show/profile/_layout/": {
      "filePath": "_authenticated/user/show/profile/_layout/index.tsx",
      "parent": "/_authenticated/user/show/profile/_layout"
    },
    "/_authenticated/user/settings/profile/edit/_layout/$idUser": {
      "filePath": "_authenticated/user/settings/profile/edit/_layout/$idUser.tsx",
      "parent": "/_authenticated/user/settings/profile/edit/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
