/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as AppIndexImport } from './routes/app/index'
import { Route as AppLayoutImport } from './routes/app/_layout'
import { Route as AuthenticatedHowItWorksImport } from './routes/_authenticated/how-it-works'
import { Route as AuthenticatedFeaturesImport } from './routes/_authenticated/features'
import { Route as AuthenticatedContactUsImport } from './routes/_authenticated/contact-us'
import { Route as authSignInImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordImport } from './routes/(auth)/reset-password'
import { Route as authCallbackImport } from './routes/(auth)/callback'
import { Route as auth500Import } from './routes/(auth)/500'
import { Route as ExampleModelIfcIndexImport } from './routes/example-model/ifc/index'
import { Route as AuthenticatedViewerIndexImport } from './routes/_authenticated/viewer/index'
import { Route as AuthenticatedMyRoom3dIndexImport } from './routes/_authenticated/my-room-3d/index'
import { Route as AppLayoutHowItWorksImport } from './routes/app/_layout/how-it-works'
import { Route as AppLayoutFeaturesImport } from './routes/app/_layout/features'
import { Route as AppLayoutContactUsImport } from './routes/app/_layout/contact-us'
import { Route as AppLayoutConnectorsImport } from './routes/app/_layout/connectors'
import { Route as AuthenticatedViewerFileCodeImport } from './routes/_authenticated/viewer/$fileCode'
import { Route as AuthenticatedManagementsMeImport } from './routes/_authenticated/managements/me'
import { Route as AuthenticatedBimViewerUtWebglClippingV2Import } from './routes/_authenticated/bim-viewer-ut/webgl-clipping-v2'
import { Route as AuthenticatedBimViewerUtWebglClippingV1Import } from './routes/_authenticated/bim-viewer-ut/webgl-clipping-v1'
import { Route as AuthenticatedBimViewerUtWebglClippingStencilIfcImport } from './routes/_authenticated/bim-viewer-ut/webgl-clipping-stencil-ifc'
import { Route as AuthenticatedBimViewerUtWebglClippingStencilImport } from './routes/_authenticated/bim-viewer-ut/webgl-clipping-stencil'
import { Route as AuthenticatedBimViewerUtWebglClippingCubeImport } from './routes/_authenticated/bim-viewer-ut/webgl-clipping-cube'
import { Route as AuthenticatedBimViewerUtViewCubeImport } from './routes/_authenticated/bim-viewer-ut/view-cube'
import { Route as AuthenticatedBimViewerUtIfcViewerSelectionFamilyImport } from './routes/_authenticated/bim-viewer-ut/ifc-viewer-selection-family'
import { Route as AuthenticatedBimViewerUtGeometrySceneViewcubeImport } from './routes/_authenticated/bim-viewer-ut/geometry-scene-viewcube'
import { Route as AuthenticatedBimViewerUtIfcViewerSelectionImport } from './routes/_authenticated/bim-viewer-ut/Ifc-viewer-selection'
import { Route as AuthenticatedViewerUploadIndexImport } from './routes/_authenticated/viewer/upload/index'

// Create Virtual Routes

const AppImport = createFileRoute('/app')()
const AuthenticatedIndexLazyImport = createFileRoute('/_authenticated/')()
const errors503LazyImport = createFileRoute('/(errors)/503')()
const errors500LazyImport = createFileRoute('/(errors)/500')()
const errors404LazyImport = createFileRoute('/(errors)/404')()
const errors403LazyImport = createFileRoute('/(errors)/403')()
const errors401LazyImport = createFileRoute('/(errors)/401')()
const authSignUpLazyImport = createFileRoute('/(auth)/sign-up')()
const authSignIn2LazyImport = createFileRoute('/(auth)/sign-in-2')()
const authForgotPasswordLazyImport = createFileRoute(
  '/(auth)/forgot-password',
)()
const AuthenticatedBimViewerUtViewerLazyImport = createFileRoute(
  '/_authenticated/bim-viewer-ut/viewer',
)()
const AuthenticatedBimViewerUtInstancedMeshLazyImport = createFileRoute(
  '/_authenticated/bim-viewer-ut/instanced-mesh',
)()
const AuthenticatedBimViewerUtIfcLoaderLazyImport = createFileRoute(
  '/_authenticated/bim-viewer-ut/ifc-loader',
)()

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexLazyRoute = AuthenticatedIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/index.lazy').then((d) => d.Route),
)

const AppIndexRoute = AppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)

const errors503LazyRoute = errors503LazyImport
  .update({
    id: '/(errors)/503',
    path: '/503',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/503.lazy').then((d) => d.Route))

const errors500LazyRoute = errors500LazyImport
  .update({
    id: '/(errors)/500',
    path: '/500',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/500.lazy').then((d) => d.Route))

const errors404LazyRoute = errors404LazyImport
  .update({
    id: '/(errors)/404',
    path: '/404',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/404.lazy').then((d) => d.Route))

const errors403LazyRoute = errors403LazyImport
  .update({
    id: '/(errors)/403',
    path: '/403',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/403.lazy').then((d) => d.Route))

const errors401LazyRoute = errors401LazyImport
  .update({
    id: '/(errors)/401',
    path: '/401',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/401.lazy').then((d) => d.Route))

const authSignUpLazyRoute = authSignUpLazyImport
  .update({
    id: '/(auth)/sign-up',
    path: '/sign-up',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-up.lazy').then((d) => d.Route))

const authSignIn2LazyRoute = authSignIn2LazyImport
  .update({
    id: '/(auth)/sign-in-2',
    path: '/sign-in-2',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-in-2.lazy').then((d) => d.Route))

const authForgotPasswordLazyRoute = authForgotPasswordLazyImport
  .update({
    id: '/(auth)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/forgot-password.lazy').then((d) => d.Route),
  )

const AppLayoutRoute = AppLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AppRoute,
} as any)

const AuthenticatedHowItWorksRoute = AuthenticatedHowItWorksImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedFeaturesRoute = AuthenticatedFeaturesImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedContactUsRoute = AuthenticatedContactUsImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const authSignInRoute = authSignInImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const authResetPasswordRoute = authResetPasswordImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const authCallbackRoute = authCallbackImport.update({
  id: '/(auth)/callback',
  path: '/callback',
  getParentRoute: () => rootRoute,
} as any)

const auth500Route = auth500Import.update({
  id: '/(auth)/500',
  path: '/500',
  getParentRoute: () => rootRoute,
} as any)

const ExampleModelIfcIndexRoute = ExampleModelIfcIndexImport.update({
  id: '/example-model/ifc/',
  path: '/example-model/ifc/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedViewerIndexRoute = AuthenticatedViewerIndexImport.update({
  id: '/viewer/',
  path: '/viewer/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedMyRoom3dIndexRoute = AuthenticatedMyRoom3dIndexImport.update(
  {
    id: '/my-room-3d/',
    path: '/my-room-3d/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
)

const AuthenticatedBimViewerUtViewerLazyRoute =
  AuthenticatedBimViewerUtViewerLazyImport.update({
    id: '/bim-viewer-ut/viewer',
    path: '/bim-viewer-ut/viewer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/bim-viewer-ut/viewer.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedBimViewerUtInstancedMeshLazyRoute =
  AuthenticatedBimViewerUtInstancedMeshLazyImport.update({
    id: '/bim-viewer-ut/instanced-mesh',
    path: '/bim-viewer-ut/instanced-mesh',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/bim-viewer-ut/instanced-mesh.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedBimViewerUtIfcLoaderLazyRoute =
  AuthenticatedBimViewerUtIfcLoaderLazyImport.update({
    id: '/bim-viewer-ut/ifc-loader',
    path: '/bim-viewer-ut/ifc-loader',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/bim-viewer-ut/ifc-loader.lazy').then(
      (d) => d.Route,
    ),
  )

const AppLayoutHowItWorksRoute = AppLayoutHowItWorksImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AppLayoutFeaturesRoute = AppLayoutFeaturesImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AppLayoutContactUsRoute = AppLayoutContactUsImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AppLayoutConnectorsRoute = AppLayoutConnectorsImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AuthenticatedViewerFileCodeRoute =
  AuthenticatedViewerFileCodeImport.update({
    id: '/viewer/$fileCode',
    path: '/viewer/$fileCode',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedManagementsMeRoute = AuthenticatedManagementsMeImport.update(
  {
    id: '/managements/me',
    path: '/managements/me',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
)

const AuthenticatedBimViewerUtWebglClippingV2Route =
  AuthenticatedBimViewerUtWebglClippingV2Import.update({
    id: '/bim-viewer-ut/webgl-clipping-v2',
    path: '/bim-viewer-ut/webgl-clipping-v2',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedBimViewerUtWebglClippingV1Route =
  AuthenticatedBimViewerUtWebglClippingV1Import.update({
    id: '/bim-viewer-ut/webgl-clipping-v1',
    path: '/bim-viewer-ut/webgl-clipping-v1',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedBimViewerUtWebglClippingStencilIfcRoute =
  AuthenticatedBimViewerUtWebglClippingStencilIfcImport.update({
    id: '/bim-viewer-ut/webgl-clipping-stencil-ifc',
    path: '/bim-viewer-ut/webgl-clipping-stencil-ifc',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedBimViewerUtWebglClippingStencilRoute =
  AuthenticatedBimViewerUtWebglClippingStencilImport.update({
    id: '/bim-viewer-ut/webgl-clipping-stencil',
    path: '/bim-viewer-ut/webgl-clipping-stencil',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedBimViewerUtWebglClippingCubeRoute =
  AuthenticatedBimViewerUtWebglClippingCubeImport.update({
    id: '/bim-viewer-ut/webgl-clipping-cube',
    path: '/bim-viewer-ut/webgl-clipping-cube',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedBimViewerUtViewCubeRoute =
  AuthenticatedBimViewerUtViewCubeImport.update({
    id: '/bim-viewer-ut/view-cube',
    path: '/bim-viewer-ut/view-cube',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedBimViewerUtIfcViewerSelectionFamilyRoute =
  AuthenticatedBimViewerUtIfcViewerSelectionFamilyImport.update({
    id: '/bim-viewer-ut/ifc-viewer-selection-family',
    path: '/bim-viewer-ut/ifc-viewer-selection-family',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedBimViewerUtGeometrySceneViewcubeRoute =
  AuthenticatedBimViewerUtGeometrySceneViewcubeImport.update({
    id: '/bim-viewer-ut/geometry-scene-viewcube',
    path: '/bim-viewer-ut/geometry-scene-viewcube',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedBimViewerUtIfcViewerSelectionRoute =
  AuthenticatedBimViewerUtIfcViewerSelectionImport.update({
    id: '/bim-viewer-ut/Ifc-viewer-selection',
    path: '/bim-viewer-ut/Ifc-viewer-selection',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedViewerUploadIndexRoute =
  AuthenticatedViewerUploadIndexImport.update({
    id: '/viewer/upload/',
    path: '/viewer/upload/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/500': {
      id: '/(auth)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof auth500Import
      parentRoute: typeof rootRoute
    }
    '/(auth)/callback': {
      id: '/(auth)/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof authCallbackImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/contact-us': {
      id: '/_authenticated/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof AuthenticatedContactUsImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/features': {
      id: '/_authenticated/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof AuthenticatedFeaturesImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/how-it-works': {
      id: '/_authenticated/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof AuthenticatedHowItWorksImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/app/_layout': {
      id: '/app/_layout'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppLayoutImport
      parentRoute: typeof AppRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2LazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpLazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503LazyImport
      parentRoute: typeof rootRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/bim-viewer-ut/Ifc-viewer-selection': {
      id: '/_authenticated/bim-viewer-ut/Ifc-viewer-selection'
      path: '/bim-viewer-ut/Ifc-viewer-selection'
      fullPath: '/bim-viewer-ut/Ifc-viewer-selection'
      preLoaderRoute: typeof AuthenticatedBimViewerUtIfcViewerSelectionImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/bim-viewer-ut/geometry-scene-viewcube': {
      id: '/_authenticated/bim-viewer-ut/geometry-scene-viewcube'
      path: '/bim-viewer-ut/geometry-scene-viewcube'
      fullPath: '/bim-viewer-ut/geometry-scene-viewcube'
      preLoaderRoute: typeof AuthenticatedBimViewerUtGeometrySceneViewcubeImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/bim-viewer-ut/ifc-viewer-selection-family': {
      id: '/_authenticated/bim-viewer-ut/ifc-viewer-selection-family'
      path: '/bim-viewer-ut/ifc-viewer-selection-family'
      fullPath: '/bim-viewer-ut/ifc-viewer-selection-family'
      preLoaderRoute: typeof AuthenticatedBimViewerUtIfcViewerSelectionFamilyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/bim-viewer-ut/view-cube': {
      id: '/_authenticated/bim-viewer-ut/view-cube'
      path: '/bim-viewer-ut/view-cube'
      fullPath: '/bim-viewer-ut/view-cube'
      preLoaderRoute: typeof AuthenticatedBimViewerUtViewCubeImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/bim-viewer-ut/webgl-clipping-cube': {
      id: '/_authenticated/bim-viewer-ut/webgl-clipping-cube'
      path: '/bim-viewer-ut/webgl-clipping-cube'
      fullPath: '/bim-viewer-ut/webgl-clipping-cube'
      preLoaderRoute: typeof AuthenticatedBimViewerUtWebglClippingCubeImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/bim-viewer-ut/webgl-clipping-stencil': {
      id: '/_authenticated/bim-viewer-ut/webgl-clipping-stencil'
      path: '/bim-viewer-ut/webgl-clipping-stencil'
      fullPath: '/bim-viewer-ut/webgl-clipping-stencil'
      preLoaderRoute: typeof AuthenticatedBimViewerUtWebglClippingStencilImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/bim-viewer-ut/webgl-clipping-stencil-ifc': {
      id: '/_authenticated/bim-viewer-ut/webgl-clipping-stencil-ifc'
      path: '/bim-viewer-ut/webgl-clipping-stencil-ifc'
      fullPath: '/bim-viewer-ut/webgl-clipping-stencil-ifc'
      preLoaderRoute: typeof AuthenticatedBimViewerUtWebglClippingStencilIfcImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/bim-viewer-ut/webgl-clipping-v1': {
      id: '/_authenticated/bim-viewer-ut/webgl-clipping-v1'
      path: '/bim-viewer-ut/webgl-clipping-v1'
      fullPath: '/bim-viewer-ut/webgl-clipping-v1'
      preLoaderRoute: typeof AuthenticatedBimViewerUtWebglClippingV1Import
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/bim-viewer-ut/webgl-clipping-v2': {
      id: '/_authenticated/bim-viewer-ut/webgl-clipping-v2'
      path: '/bim-viewer-ut/webgl-clipping-v2'
      fullPath: '/bim-viewer-ut/webgl-clipping-v2'
      preLoaderRoute: typeof AuthenticatedBimViewerUtWebglClippingV2Import
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/managements/me': {
      id: '/_authenticated/managements/me'
      path: '/managements/me'
      fullPath: '/managements/me'
      preLoaderRoute: typeof AuthenticatedManagementsMeImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/viewer/$fileCode': {
      id: '/_authenticated/viewer/$fileCode'
      path: '/viewer/$fileCode'
      fullPath: '/viewer/$fileCode'
      preLoaderRoute: typeof AuthenticatedViewerFileCodeImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/app/_layout/connectors': {
      id: '/app/_layout/connectors'
      path: '/connectors'
      fullPath: '/app/connectors'
      preLoaderRoute: typeof AppLayoutConnectorsImport
      parentRoute: typeof AppLayoutImport
    }
    '/app/_layout/contact-us': {
      id: '/app/_layout/contact-us'
      path: '/contact-us'
      fullPath: '/app/contact-us'
      preLoaderRoute: typeof AppLayoutContactUsImport
      parentRoute: typeof AppLayoutImport
    }
    '/app/_layout/features': {
      id: '/app/_layout/features'
      path: '/features'
      fullPath: '/app/features'
      preLoaderRoute: typeof AppLayoutFeaturesImport
      parentRoute: typeof AppLayoutImport
    }
    '/app/_layout/how-it-works': {
      id: '/app/_layout/how-it-works'
      path: '/how-it-works'
      fullPath: '/app/how-it-works'
      preLoaderRoute: typeof AppLayoutHowItWorksImport
      parentRoute: typeof AppLayoutImport
    }
    '/_authenticated/bim-viewer-ut/ifc-loader': {
      id: '/_authenticated/bim-viewer-ut/ifc-loader'
      path: '/bim-viewer-ut/ifc-loader'
      fullPath: '/bim-viewer-ut/ifc-loader'
      preLoaderRoute: typeof AuthenticatedBimViewerUtIfcLoaderLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/bim-viewer-ut/instanced-mesh': {
      id: '/_authenticated/bim-viewer-ut/instanced-mesh'
      path: '/bim-viewer-ut/instanced-mesh'
      fullPath: '/bim-viewer-ut/instanced-mesh'
      preLoaderRoute: typeof AuthenticatedBimViewerUtInstancedMeshLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/bim-viewer-ut/viewer': {
      id: '/_authenticated/bim-viewer-ut/viewer'
      path: '/bim-viewer-ut/viewer'
      fullPath: '/bim-viewer-ut/viewer'
      preLoaderRoute: typeof AuthenticatedBimViewerUtViewerLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/my-room-3d/': {
      id: '/_authenticated/my-room-3d/'
      path: '/my-room-3d'
      fullPath: '/my-room-3d'
      preLoaderRoute: typeof AuthenticatedMyRoom3dIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/viewer/': {
      id: '/_authenticated/viewer/'
      path: '/viewer'
      fullPath: '/viewer'
      preLoaderRoute: typeof AuthenticatedViewerIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/example-model/ifc/': {
      id: '/example-model/ifc/'
      path: '/example-model/ifc'
      fullPath: '/example-model/ifc'
      preLoaderRoute: typeof ExampleModelIfcIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/viewer/upload/': {
      id: '/_authenticated/viewer/upload/'
      path: '/viewer/upload'
      fullPath: '/viewer/upload'
      preLoaderRoute: typeof AuthenticatedViewerUploadIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteRouteChildren {
  AuthenticatedContactUsRoute: typeof AuthenticatedContactUsRoute
  AuthenticatedFeaturesRoute: typeof AuthenticatedFeaturesRoute
  AuthenticatedHowItWorksRoute: typeof AuthenticatedHowItWorksRoute
  AuthenticatedIndexLazyRoute: typeof AuthenticatedIndexLazyRoute
  AuthenticatedBimViewerUtIfcViewerSelectionRoute: typeof AuthenticatedBimViewerUtIfcViewerSelectionRoute
  AuthenticatedBimViewerUtGeometrySceneViewcubeRoute: typeof AuthenticatedBimViewerUtGeometrySceneViewcubeRoute
  AuthenticatedBimViewerUtIfcViewerSelectionFamilyRoute: typeof AuthenticatedBimViewerUtIfcViewerSelectionFamilyRoute
  AuthenticatedBimViewerUtViewCubeRoute: typeof AuthenticatedBimViewerUtViewCubeRoute
  AuthenticatedBimViewerUtWebglClippingCubeRoute: typeof AuthenticatedBimViewerUtWebglClippingCubeRoute
  AuthenticatedBimViewerUtWebglClippingStencilRoute: typeof AuthenticatedBimViewerUtWebglClippingStencilRoute
  AuthenticatedBimViewerUtWebglClippingStencilIfcRoute: typeof AuthenticatedBimViewerUtWebglClippingStencilIfcRoute
  AuthenticatedBimViewerUtWebglClippingV1Route: typeof AuthenticatedBimViewerUtWebglClippingV1Route
  AuthenticatedBimViewerUtWebglClippingV2Route: typeof AuthenticatedBimViewerUtWebglClippingV2Route
  AuthenticatedManagementsMeRoute: typeof AuthenticatedManagementsMeRoute
  AuthenticatedViewerFileCodeRoute: typeof AuthenticatedViewerFileCodeRoute
  AuthenticatedBimViewerUtIfcLoaderLazyRoute: typeof AuthenticatedBimViewerUtIfcLoaderLazyRoute
  AuthenticatedBimViewerUtInstancedMeshLazyRoute: typeof AuthenticatedBimViewerUtInstancedMeshLazyRoute
  AuthenticatedBimViewerUtViewerLazyRoute: typeof AuthenticatedBimViewerUtViewerLazyRoute
  AuthenticatedMyRoom3dIndexRoute: typeof AuthenticatedMyRoom3dIndexRoute
  AuthenticatedViewerIndexRoute: typeof AuthenticatedViewerIndexRoute
  AuthenticatedViewerUploadIndexRoute: typeof AuthenticatedViewerUploadIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedContactUsRoute: AuthenticatedContactUsRoute,
  AuthenticatedFeaturesRoute: AuthenticatedFeaturesRoute,
  AuthenticatedHowItWorksRoute: AuthenticatedHowItWorksRoute,
  AuthenticatedIndexLazyRoute: AuthenticatedIndexLazyRoute,
  AuthenticatedBimViewerUtIfcViewerSelectionRoute:
    AuthenticatedBimViewerUtIfcViewerSelectionRoute,
  AuthenticatedBimViewerUtGeometrySceneViewcubeRoute:
    AuthenticatedBimViewerUtGeometrySceneViewcubeRoute,
  AuthenticatedBimViewerUtIfcViewerSelectionFamilyRoute:
    AuthenticatedBimViewerUtIfcViewerSelectionFamilyRoute,
  AuthenticatedBimViewerUtViewCubeRoute: AuthenticatedBimViewerUtViewCubeRoute,
  AuthenticatedBimViewerUtWebglClippingCubeRoute:
    AuthenticatedBimViewerUtWebglClippingCubeRoute,
  AuthenticatedBimViewerUtWebglClippingStencilRoute:
    AuthenticatedBimViewerUtWebglClippingStencilRoute,
  AuthenticatedBimViewerUtWebglClippingStencilIfcRoute:
    AuthenticatedBimViewerUtWebglClippingStencilIfcRoute,
  AuthenticatedBimViewerUtWebglClippingV1Route:
    AuthenticatedBimViewerUtWebglClippingV1Route,
  AuthenticatedBimViewerUtWebglClippingV2Route:
    AuthenticatedBimViewerUtWebglClippingV2Route,
  AuthenticatedManagementsMeRoute: AuthenticatedManagementsMeRoute,
  AuthenticatedViewerFileCodeRoute: AuthenticatedViewerFileCodeRoute,
  AuthenticatedBimViewerUtIfcLoaderLazyRoute:
    AuthenticatedBimViewerUtIfcLoaderLazyRoute,
  AuthenticatedBimViewerUtInstancedMeshLazyRoute:
    AuthenticatedBimViewerUtInstancedMeshLazyRoute,
  AuthenticatedBimViewerUtViewerLazyRoute:
    AuthenticatedBimViewerUtViewerLazyRoute,
  AuthenticatedMyRoom3dIndexRoute: AuthenticatedMyRoom3dIndexRoute,
  AuthenticatedViewerIndexRoute: AuthenticatedViewerIndexRoute,
  AuthenticatedViewerUploadIndexRoute: AuthenticatedViewerUploadIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AppLayoutRouteChildren {
  AppLayoutConnectorsRoute: typeof AppLayoutConnectorsRoute
  AppLayoutContactUsRoute: typeof AppLayoutContactUsRoute
  AppLayoutFeaturesRoute: typeof AppLayoutFeaturesRoute
  AppLayoutHowItWorksRoute: typeof AppLayoutHowItWorksRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppLayoutConnectorsRoute: AppLayoutConnectorsRoute,
  AppLayoutContactUsRoute: AppLayoutContactUsRoute,
  AppLayoutFeaturesRoute: AppLayoutFeaturesRoute,
  AppLayoutHowItWorksRoute: AppLayoutHowItWorksRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface AppRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteRouteWithChildren
  '/500': typeof errors500LazyRoute
  '/callback': typeof authCallbackRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/contact-us': typeof AuthenticatedContactUsRoute
  '/features': typeof AuthenticatedFeaturesRoute
  '/how-it-works': typeof AuthenticatedHowItWorksRoute
  '/app': typeof AppLayoutRouteWithChildren
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-in-2': typeof authSignIn2LazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/503': typeof errors503LazyRoute
  '/app/': typeof AppIndexRoute
  '/': typeof AuthenticatedIndexLazyRoute
  '/bim-viewer-ut/Ifc-viewer-selection': typeof AuthenticatedBimViewerUtIfcViewerSelectionRoute
  '/bim-viewer-ut/geometry-scene-viewcube': typeof AuthenticatedBimViewerUtGeometrySceneViewcubeRoute
  '/bim-viewer-ut/ifc-viewer-selection-family': typeof AuthenticatedBimViewerUtIfcViewerSelectionFamilyRoute
  '/bim-viewer-ut/view-cube': typeof AuthenticatedBimViewerUtViewCubeRoute
  '/bim-viewer-ut/webgl-clipping-cube': typeof AuthenticatedBimViewerUtWebglClippingCubeRoute
  '/bim-viewer-ut/webgl-clipping-stencil': typeof AuthenticatedBimViewerUtWebglClippingStencilRoute
  '/bim-viewer-ut/webgl-clipping-stencil-ifc': typeof AuthenticatedBimViewerUtWebglClippingStencilIfcRoute
  '/bim-viewer-ut/webgl-clipping-v1': typeof AuthenticatedBimViewerUtWebglClippingV1Route
  '/bim-viewer-ut/webgl-clipping-v2': typeof AuthenticatedBimViewerUtWebglClippingV2Route
  '/managements/me': typeof AuthenticatedManagementsMeRoute
  '/viewer/$fileCode': typeof AuthenticatedViewerFileCodeRoute
  '/app/connectors': typeof AppLayoutConnectorsRoute
  '/app/contact-us': typeof AppLayoutContactUsRoute
  '/app/features': typeof AppLayoutFeaturesRoute
  '/app/how-it-works': typeof AppLayoutHowItWorksRoute
  '/bim-viewer-ut/ifc-loader': typeof AuthenticatedBimViewerUtIfcLoaderLazyRoute
  '/bim-viewer-ut/instanced-mesh': typeof AuthenticatedBimViewerUtInstancedMeshLazyRoute
  '/bim-viewer-ut/viewer': typeof AuthenticatedBimViewerUtViewerLazyRoute
  '/my-room-3d': typeof AuthenticatedMyRoom3dIndexRoute
  '/viewer': typeof AuthenticatedViewerIndexRoute
  '/example-model/ifc': typeof ExampleModelIfcIndexRoute
  '/viewer/upload': typeof AuthenticatedViewerUploadIndexRoute
}

export interface FileRoutesByTo {
  '/500': typeof errors500LazyRoute
  '/callback': typeof authCallbackRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/contact-us': typeof AuthenticatedContactUsRoute
  '/features': typeof AuthenticatedFeaturesRoute
  '/how-it-works': typeof AuthenticatedHowItWorksRoute
  '/app': typeof AppIndexRoute
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-in-2': typeof authSignIn2LazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/503': typeof errors503LazyRoute
  '/': typeof AuthenticatedIndexLazyRoute
  '/bim-viewer-ut/Ifc-viewer-selection': typeof AuthenticatedBimViewerUtIfcViewerSelectionRoute
  '/bim-viewer-ut/geometry-scene-viewcube': typeof AuthenticatedBimViewerUtGeometrySceneViewcubeRoute
  '/bim-viewer-ut/ifc-viewer-selection-family': typeof AuthenticatedBimViewerUtIfcViewerSelectionFamilyRoute
  '/bim-viewer-ut/view-cube': typeof AuthenticatedBimViewerUtViewCubeRoute
  '/bim-viewer-ut/webgl-clipping-cube': typeof AuthenticatedBimViewerUtWebglClippingCubeRoute
  '/bim-viewer-ut/webgl-clipping-stencil': typeof AuthenticatedBimViewerUtWebglClippingStencilRoute
  '/bim-viewer-ut/webgl-clipping-stencil-ifc': typeof AuthenticatedBimViewerUtWebglClippingStencilIfcRoute
  '/bim-viewer-ut/webgl-clipping-v1': typeof AuthenticatedBimViewerUtWebglClippingV1Route
  '/bim-viewer-ut/webgl-clipping-v2': typeof AuthenticatedBimViewerUtWebglClippingV2Route
  '/managements/me': typeof AuthenticatedManagementsMeRoute
  '/viewer/$fileCode': typeof AuthenticatedViewerFileCodeRoute
  '/app/connectors': typeof AppLayoutConnectorsRoute
  '/app/contact-us': typeof AppLayoutContactUsRoute
  '/app/features': typeof AppLayoutFeaturesRoute
  '/app/how-it-works': typeof AppLayoutHowItWorksRoute
  '/bim-viewer-ut/ifc-loader': typeof AuthenticatedBimViewerUtIfcLoaderLazyRoute
  '/bim-viewer-ut/instanced-mesh': typeof AuthenticatedBimViewerUtInstancedMeshLazyRoute
  '/bim-viewer-ut/viewer': typeof AuthenticatedBimViewerUtViewerLazyRoute
  '/my-room-3d': typeof AuthenticatedMyRoom3dIndexRoute
  '/viewer': typeof AuthenticatedViewerIndexRoute
  '/example-model/ifc': typeof ExampleModelIfcIndexRoute
  '/viewer/upload': typeof AuthenticatedViewerUploadIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/500': typeof auth500Route
  '/(auth)/callback': typeof authCallbackRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/contact-us': typeof AuthenticatedContactUsRoute
  '/_authenticated/features': typeof AuthenticatedFeaturesRoute
  '/_authenticated/how-it-works': typeof AuthenticatedHowItWorksRoute
  '/app': typeof AppRouteWithChildren
  '/app/_layout': typeof AppLayoutRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordLazyRoute
  '/(auth)/sign-in-2': typeof authSignIn2LazyRoute
  '/(auth)/sign-up': typeof authSignUpLazyRoute
  '/(errors)/401': typeof errors401LazyRoute
  '/(errors)/403': typeof errors403LazyRoute
  '/(errors)/404': typeof errors404LazyRoute
  '/(errors)/500': typeof errors500LazyRoute
  '/(errors)/503': typeof errors503LazyRoute
  '/app/': typeof AppIndexRoute
  '/_authenticated/': typeof AuthenticatedIndexLazyRoute
  '/_authenticated/bim-viewer-ut/Ifc-viewer-selection': typeof AuthenticatedBimViewerUtIfcViewerSelectionRoute
  '/_authenticated/bim-viewer-ut/geometry-scene-viewcube': typeof AuthenticatedBimViewerUtGeometrySceneViewcubeRoute
  '/_authenticated/bim-viewer-ut/ifc-viewer-selection-family': typeof AuthenticatedBimViewerUtIfcViewerSelectionFamilyRoute
  '/_authenticated/bim-viewer-ut/view-cube': typeof AuthenticatedBimViewerUtViewCubeRoute
  '/_authenticated/bim-viewer-ut/webgl-clipping-cube': typeof AuthenticatedBimViewerUtWebglClippingCubeRoute
  '/_authenticated/bim-viewer-ut/webgl-clipping-stencil': typeof AuthenticatedBimViewerUtWebglClippingStencilRoute
  '/_authenticated/bim-viewer-ut/webgl-clipping-stencil-ifc': typeof AuthenticatedBimViewerUtWebglClippingStencilIfcRoute
  '/_authenticated/bim-viewer-ut/webgl-clipping-v1': typeof AuthenticatedBimViewerUtWebglClippingV1Route
  '/_authenticated/bim-viewer-ut/webgl-clipping-v2': typeof AuthenticatedBimViewerUtWebglClippingV2Route
  '/_authenticated/managements/me': typeof AuthenticatedManagementsMeRoute
  '/_authenticated/viewer/$fileCode': typeof AuthenticatedViewerFileCodeRoute
  '/app/_layout/connectors': typeof AppLayoutConnectorsRoute
  '/app/_layout/contact-us': typeof AppLayoutContactUsRoute
  '/app/_layout/features': typeof AppLayoutFeaturesRoute
  '/app/_layout/how-it-works': typeof AppLayoutHowItWorksRoute
  '/_authenticated/bim-viewer-ut/ifc-loader': typeof AuthenticatedBimViewerUtIfcLoaderLazyRoute
  '/_authenticated/bim-viewer-ut/instanced-mesh': typeof AuthenticatedBimViewerUtInstancedMeshLazyRoute
  '/_authenticated/bim-viewer-ut/viewer': typeof AuthenticatedBimViewerUtViewerLazyRoute
  '/_authenticated/my-room-3d/': typeof AuthenticatedMyRoom3dIndexRoute
  '/_authenticated/viewer/': typeof AuthenticatedViewerIndexRoute
  '/example-model/ifc/': typeof ExampleModelIfcIndexRoute
  '/_authenticated/viewer/upload/': typeof AuthenticatedViewerUploadIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/500'
    | '/callback'
    | '/reset-password'
    | '/sign-in'
    | '/contact-us'
    | '/features'
    | '/how-it-works'
    | '/app'
    | '/forgot-password'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/503'
    | '/app/'
    | '/'
    | '/bim-viewer-ut/Ifc-viewer-selection'
    | '/bim-viewer-ut/geometry-scene-viewcube'
    | '/bim-viewer-ut/ifc-viewer-selection-family'
    | '/bim-viewer-ut/view-cube'
    | '/bim-viewer-ut/webgl-clipping-cube'
    | '/bim-viewer-ut/webgl-clipping-stencil'
    | '/bim-viewer-ut/webgl-clipping-stencil-ifc'
    | '/bim-viewer-ut/webgl-clipping-v1'
    | '/bim-viewer-ut/webgl-clipping-v2'
    | '/managements/me'
    | '/viewer/$fileCode'
    | '/app/connectors'
    | '/app/contact-us'
    | '/app/features'
    | '/app/how-it-works'
    | '/bim-viewer-ut/ifc-loader'
    | '/bim-viewer-ut/instanced-mesh'
    | '/bim-viewer-ut/viewer'
    | '/my-room-3d'
    | '/viewer'
    | '/example-model/ifc'
    | '/viewer/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/500'
    | '/callback'
    | '/reset-password'
    | '/sign-in'
    | '/contact-us'
    | '/features'
    | '/how-it-works'
    | '/app'
    | '/forgot-password'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/503'
    | '/'
    | '/bim-viewer-ut/Ifc-viewer-selection'
    | '/bim-viewer-ut/geometry-scene-viewcube'
    | '/bim-viewer-ut/ifc-viewer-selection-family'
    | '/bim-viewer-ut/view-cube'
    | '/bim-viewer-ut/webgl-clipping-cube'
    | '/bim-viewer-ut/webgl-clipping-stencil'
    | '/bim-viewer-ut/webgl-clipping-stencil-ifc'
    | '/bim-viewer-ut/webgl-clipping-v1'
    | '/bim-viewer-ut/webgl-clipping-v2'
    | '/managements/me'
    | '/viewer/$fileCode'
    | '/app/connectors'
    | '/app/contact-us'
    | '/app/features'
    | '/app/how-it-works'
    | '/bim-viewer-ut/ifc-loader'
    | '/bim-viewer-ut/instanced-mesh'
    | '/bim-viewer-ut/viewer'
    | '/my-room-3d'
    | '/viewer'
    | '/example-model/ifc'
    | '/viewer/upload'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/500'
    | '/(auth)/callback'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/_authenticated/contact-us'
    | '/_authenticated/features'
    | '/_authenticated/how-it-works'
    | '/app'
    | '/app/_layout'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/app/'
    | '/_authenticated/'
    | '/_authenticated/bim-viewer-ut/Ifc-viewer-selection'
    | '/_authenticated/bim-viewer-ut/geometry-scene-viewcube'
    | '/_authenticated/bim-viewer-ut/ifc-viewer-selection-family'
    | '/_authenticated/bim-viewer-ut/view-cube'
    | '/_authenticated/bim-viewer-ut/webgl-clipping-cube'
    | '/_authenticated/bim-viewer-ut/webgl-clipping-stencil'
    | '/_authenticated/bim-viewer-ut/webgl-clipping-stencil-ifc'
    | '/_authenticated/bim-viewer-ut/webgl-clipping-v1'
    | '/_authenticated/bim-viewer-ut/webgl-clipping-v2'
    | '/_authenticated/managements/me'
    | '/_authenticated/viewer/$fileCode'
    | '/app/_layout/connectors'
    | '/app/_layout/contact-us'
    | '/app/_layout/features'
    | '/app/_layout/how-it-works'
    | '/_authenticated/bim-viewer-ut/ifc-loader'
    | '/_authenticated/bim-viewer-ut/instanced-mesh'
    | '/_authenticated/bim-viewer-ut/viewer'
    | '/_authenticated/my-room-3d/'
    | '/_authenticated/viewer/'
    | '/example-model/ifc/'
    | '/_authenticated/viewer/upload/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  auth500Route: typeof auth500Route
  authCallbackRoute: typeof authCallbackRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  AppRoute: typeof AppRouteWithChildren
  authForgotPasswordLazyRoute: typeof authForgotPasswordLazyRoute
  authSignIn2LazyRoute: typeof authSignIn2LazyRoute
  authSignUpLazyRoute: typeof authSignUpLazyRoute
  errors401LazyRoute: typeof errors401LazyRoute
  errors403LazyRoute: typeof errors403LazyRoute
  errors404LazyRoute: typeof errors404LazyRoute
  errors500LazyRoute: typeof errors500LazyRoute
  errors503LazyRoute: typeof errors503LazyRoute
  ExampleModelIfcIndexRoute: typeof ExampleModelIfcIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  auth500Route: auth500Route,
  authCallbackRoute: authCallbackRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  AppRoute: AppRouteWithChildren,
  authForgotPasswordLazyRoute: authForgotPasswordLazyRoute,
  authSignIn2LazyRoute: authSignIn2LazyRoute,
  authSignUpLazyRoute: authSignUpLazyRoute,
  errors401LazyRoute: errors401LazyRoute,
  errors403LazyRoute: errors403LazyRoute,
  errors404LazyRoute: errors404LazyRoute,
  errors500LazyRoute: errors500LazyRoute,
  errors503LazyRoute: errors503LazyRoute,
  ExampleModelIfcIndexRoute: ExampleModelIfcIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/(auth)/500",
        "/(auth)/callback",
        "/(auth)/reset-password",
        "/(auth)/sign-in",
        "/app",
        "/(auth)/forgot-password",
        "/(auth)/sign-in-2",
        "/(auth)/sign-up",
        "/(errors)/401",
        "/(errors)/403",
        "/(errors)/404",
        "/(errors)/500",
        "/(errors)/503",
        "/example-model/ifc/"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/contact-us",
        "/_authenticated/features",
        "/_authenticated/how-it-works",
        "/_authenticated/",
        "/_authenticated/bim-viewer-ut/Ifc-viewer-selection",
        "/_authenticated/bim-viewer-ut/geometry-scene-viewcube",
        "/_authenticated/bim-viewer-ut/ifc-viewer-selection-family",
        "/_authenticated/bim-viewer-ut/view-cube",
        "/_authenticated/bim-viewer-ut/webgl-clipping-cube",
        "/_authenticated/bim-viewer-ut/webgl-clipping-stencil",
        "/_authenticated/bim-viewer-ut/webgl-clipping-stencil-ifc",
        "/_authenticated/bim-viewer-ut/webgl-clipping-v1",
        "/_authenticated/bim-viewer-ut/webgl-clipping-v2",
        "/_authenticated/managements/me",
        "/_authenticated/viewer/$fileCode",
        "/_authenticated/bim-viewer-ut/ifc-loader",
        "/_authenticated/bim-viewer-ut/instanced-mesh",
        "/_authenticated/bim-viewer-ut/viewer",
        "/_authenticated/my-room-3d/",
        "/_authenticated/viewer/",
        "/_authenticated/viewer/upload/"
      ]
    },
    "/(auth)/500": {
      "filePath": "(auth)/500.tsx"
    },
    "/(auth)/callback": {
      "filePath": "(auth)/callback.tsx"
    },
    "/(auth)/reset-password": {
      "filePath": "(auth)/reset-password.tsx"
    },
    "/(auth)/sign-in": {
      "filePath": "(auth)/sign-in.tsx"
    },
    "/_authenticated/contact-us": {
      "filePath": "_authenticated/contact-us.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/features": {
      "filePath": "_authenticated/features.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/how-it-works": {
      "filePath": "_authenticated/how-it-works.tsx",
      "parent": "/_authenticated"
    },
    "/app": {
      "filePath": "app",
      "children": [
        "/app/_layout",
        "/app/"
      ]
    },
    "/app/_layout": {
      "filePath": "app/_layout.tsx",
      "parent": "/app",
      "children": [
        "/app/_layout/connectors",
        "/app/_layout/contact-us",
        "/app/_layout/features",
        "/app/_layout/how-it-works"
      ]
    },
    "/(auth)/forgot-password": {
      "filePath": "(auth)/forgot-password.lazy.tsx"
    },
    "/(auth)/sign-in-2": {
      "filePath": "(auth)/sign-in-2.lazy.tsx"
    },
    "/(auth)/sign-up": {
      "filePath": "(auth)/sign-up.lazy.tsx"
    },
    "/(errors)/401": {
      "filePath": "(errors)/401.lazy.tsx"
    },
    "/(errors)/403": {
      "filePath": "(errors)/403.lazy.tsx"
    },
    "/(errors)/404": {
      "filePath": "(errors)/404.lazy.tsx"
    },
    "/(errors)/500": {
      "filePath": "(errors)/500.lazy.tsx"
    },
    "/(errors)/503": {
      "filePath": "(errors)/503.lazy.tsx"
    },
    "/app/": {
      "filePath": "app/index.tsx",
      "parent": "/app"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/bim-viewer-ut/Ifc-viewer-selection": {
      "filePath": "_authenticated/bim-viewer-ut/Ifc-viewer-selection.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/bim-viewer-ut/geometry-scene-viewcube": {
      "filePath": "_authenticated/bim-viewer-ut/geometry-scene-viewcube.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/bim-viewer-ut/ifc-viewer-selection-family": {
      "filePath": "_authenticated/bim-viewer-ut/ifc-viewer-selection-family.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/bim-viewer-ut/view-cube": {
      "filePath": "_authenticated/bim-viewer-ut/view-cube.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/bim-viewer-ut/webgl-clipping-cube": {
      "filePath": "_authenticated/bim-viewer-ut/webgl-clipping-cube.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/bim-viewer-ut/webgl-clipping-stencil": {
      "filePath": "_authenticated/bim-viewer-ut/webgl-clipping-stencil.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/bim-viewer-ut/webgl-clipping-stencil-ifc": {
      "filePath": "_authenticated/bim-viewer-ut/webgl-clipping-stencil-ifc.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/bim-viewer-ut/webgl-clipping-v1": {
      "filePath": "_authenticated/bim-viewer-ut/webgl-clipping-v1.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/bim-viewer-ut/webgl-clipping-v2": {
      "filePath": "_authenticated/bim-viewer-ut/webgl-clipping-v2.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/managements/me": {
      "filePath": "_authenticated/managements/me.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/viewer/$fileCode": {
      "filePath": "_authenticated/viewer/$fileCode.tsx",
      "parent": "/_authenticated"
    },
    "/app/_layout/connectors": {
      "filePath": "app/_layout/connectors.tsx",
      "parent": "/app/_layout"
    },
    "/app/_layout/contact-us": {
      "filePath": "app/_layout/contact-us.tsx",
      "parent": "/app/_layout"
    },
    "/app/_layout/features": {
      "filePath": "app/_layout/features.tsx",
      "parent": "/app/_layout"
    },
    "/app/_layout/how-it-works": {
      "filePath": "app/_layout/how-it-works.tsx",
      "parent": "/app/_layout"
    },
    "/_authenticated/bim-viewer-ut/ifc-loader": {
      "filePath": "_authenticated/bim-viewer-ut/ifc-loader.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/bim-viewer-ut/instanced-mesh": {
      "filePath": "_authenticated/bim-viewer-ut/instanced-mesh.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/bim-viewer-ut/viewer": {
      "filePath": "_authenticated/bim-viewer-ut/viewer.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/my-room-3d/": {
      "filePath": "_authenticated/my-room-3d/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/viewer/": {
      "filePath": "_authenticated/viewer/index.tsx",
      "parent": "/_authenticated"
    },
    "/example-model/ifc/": {
      "filePath": "example-model/ifc/index.ts"
    },
    "/_authenticated/viewer/upload/": {
      "filePath": "_authenticated/viewer/upload/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
