
services:
  frontend:
    build:
      context: ..
      dockerfile: .docker_202/Dockerfile
    container_name: frontend_container_202
    networks:
      - beta_network
    restart: always

  nginx_proxy:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./reverse-proxy.conf:/etc/nginx/conf.d/reverse-proxy.conf
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - beta_network
    restart: always

networks:
  beta_network:
    name: beta_network
    external: true