services:
  frontend:
    build:
      context: ..
      dockerfile: .docker_202/Dockerfile
    container_name: frontend_container_202
    expose:
      - "3003"
    networks:
      - beta_network
    restart: always

  nginx_proxy:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-frontend.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend
    networks:
      - beta_network
    restart: always

networks:
  beta_network:
    name: beta_network
    external: true