server {
    listen 80;
    server_name beta.deepbim.net;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name beta.deepbim.net;

    ssl_certificate /etc/letsencrypt/live/beta.deepbim.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/beta.deepbim.net/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}