server {
    listen 80;
    server_name beta.deepbim.net;

    # Redirect HTTP sang HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name beta.deepbim.net;

    # Đường dẫn đến chứng chỉ và khóa riêng tư
    ssl_certificate /etc/letsencrypt/live/beta.deepbim.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/beta.deepbim.net/privkey.pem;

    location / {
        proxy_pass http://frontend_container_202;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}