server {
    listen 80;
    server_name beta.deepbim.net;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri; # Chuyển hướng HTTP -> HTTPS
    }
}

server {
    listen 443 ssl;
    server_name beta.deepbim.net;

    ssl_certificate /etc/letsencrypt/live/beta.deepbim.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/beta.deepbim.net/privkey.pem;

    location / {
        proxy_pass http://frontend_container_202:80; # Proxy đến frontend container
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}